import type { Step } from './buildout-types'

/**
 * BODY RECODE SAAS: the coach platform, and what has to be true before it is
 * sold to anyone.
 *
 * Added 17 September 2026, when the order changed: Body Recode SaaS goes to
 * market first, Strenn follows. Everything here is either done this week or
 * blocks the pilot. Plan and reasoning:
 * `06_SAAS_PLATFORM_BUILD/2026-09-17_Coach_SaaS_Pilot_Plan.md`.
 *
 * Steps live here once. `build-sequence.ts` arranges them into the board's
 * stages by id and tags them with the products they serve.
 */
export const COACH_SAAS_STEPS: Step[] = [
  /* ── Shipped: safety and privacy work, 16 to 17 September ───────────── */
  {
    id: 'saas-coach-scoping',
    title: 'A coach sees only their own clients',
    description: 'Ownership enforced at four layers, with a test that proves it.',
    status: 'shipped',
    shippedAt: '2026-09-17',
    effort: 'L',
    commits: ['e97d9edc'],
    surfaces: ['src/lib/coach-scope.ts', 'src/middleware.ts', 'src/app/dashboard/layout.tsx', 'scripts/test-coach-scope.ts'],
    notes: 'THE blocker. Access was decided by "are you a coach", never "is this your client": 48 dashboard files read clients with no coach filter, on the service-role connection which bypasses row level security. Harmless with one coach, a notifiable breach with two. Now: dashboard requires a coach, the client record layout asserts ownership (covering every page under it), middleware gates all 49 client API routes, lists filter by owner. Verified live.',
  },
  {
    id: 'saas-blood-read-paused',
    title: 'Client-facing blood read switched off',
    description: 'The single feature most likely to make us a medical device, behind a flag.',
    status: 'shipped',
    shippedAt: '2026-09-17',
    effort: 'S',
    commits: ['03ddccc0'],
    surfaces: ['src/lib/blood-read-gate.ts'],
    notes: 'The TGA illustrates "information requiring a health professional" with a consumer interpreting inflammatory markers in their blood. Transcription, GP flags, coach analysis and plan influence all still run. One environment setting reverses it once the lawyer answers.',
  },
  {
    id: 'saas-consent-at-collection',
    title: 'Consent asked where health information is collected',
    description: 'A notice and an unticked box on the intake and the blood upload, both timestamped.',
    status: 'shipped',
    shippedAt: '2026-09-17',
    effort: 'M',
    commits: ['f5d6c2be'],
    surfaces: ['src/components/collection-notice.tsx', 'sql/2026-09-17_intake_health_consent.sql'],
    notes: 'Sensitive information needs consent that is specific and not bundled, and the notice has to be given at or before collection, including which countries data goes to. A footer link is neither. Consent is stored, because a tick nobody recorded is the same as no tick.',
  },
  {
    id: 'saas-privacy-policy-rewrite',
    title: 'Privacy policy rewritten and published',
    description: 'Health information listed, every provider\'s country named, automated decisions and retention sections added.',
    status: 'shipped',
    shippedAt: '2026-09-17',
    effort: 'M',
    commits: ['68599288', '713b37c4'],
    surfaces: ['src/app/privacy/page.tsx', '11_SECURITY_AND_COMPLIANCE/07_PRIVACY_POLICY.pdf'],
    notes: 'The automated decisions section becomes a legal requirement on 10 December 2026 and is in early. Record copy filed as a PDF. Draft pending the lawyer.',
  },
  {
    id: 'saas-pixel-off-client-pages',
    title: 'Advertising pixel kept off client pages',
    description: 'It was firing on the intake, portal, blood upload and check-in.',
    status: 'shipped',
    shippedAt: '2026-09-17',
    effort: 'S',
    commits: ['8d171826'],
    surfaces: ['src/components/meta-pixel.tsx'],
    notes: 'A pixel page view sends the page and referring address to Meta, and those addresses carry a client\'s private access token. The policy promised Meta receives no health information; this makes that true. Purchase tracking untouched.',
  },
  {
    id: 'saas-adults-only',
    title: 'Under 18s blocked at both entry points',
    description: 'The scorecard stops, and the intake refuses at the server.',
    status: 'shipped',
    shippedAt: '2026-09-17',
    effort: 'S',
    commits: ['0cea8c7', '76cb57a4'],
    notes: 'Open item on the peer review control sheet. Reading where a developing body holds fat risks feeding disordered eating, and the doctrine exclusions were written for adults. What a safeguarded youth version would need still waits on clinical input.',
  },
  {
    id: 'saas-retention-seven-years',
    title: 'Retention set to seven years, and the existing six re-derived',
    description: 'Code and the published promise now agree.',
    status: 'shipped',
    shippedAt: '2026-09-17',
    effort: 'S',
    commits: ['59469b86'],
    notes: 'State health records law requires seven years from last service for adult health records. Nothing is deleted by the number: it decides when a record becomes eligible, and deletion stays a deliberate act.',
  },
  {
    id: 'saas-breach-plan',
    title: 'Breach response plan',
    description: 'Contain, assess, notify, review, with a first-hour checklist.',
    status: 'shipped',
    shippedAt: '2026-09-17',
    effort: 'S',
    surfaces: ['11_SECURITY_AND_COMPLIANCE/08_BREACH_RESPONSE_PLAN.pdf'],
    notes: 'Written to be followed by one person under pressure. States what is not yet true: no insurance, no licensee breach terms, never tested.',
  },
  {
    id: 'saas-processor-register',
    title: 'Data processors verified, and what sits outside the system',
    description: 'Every provider, its country, and the Dropbox and email copies the platform cannot reach.',
    status: 'shipped',
    shippedAt: '2026-09-17',
    effort: 'M',
    surfaces: ['11_SECURITY_AND_COMPLIANCE/04_DATA_PROCESSORS.md', '11_SECURITY_AND_COMPLIANCE/09_RECORDS_OUTSIDE_THE_SYSTEM.md'],
    notes: 'Supabase confirmed in Sydney. Zoom records nothing and its credentials are write-only. 46 shared links audited, none touching client data. Five client folders in Dropbox hold health documents outside the retention rule.',
  },

  /* ── Before a second coach signs in ──────────────────────────────────── */
  {
    id: 'saas-rls-alignment',
    title: 'Database policies match the ownership model',
    description: 'The second layer behind the service-role connection.',
    status: 'planned',
    effort: 'M',
    blockedBy: 'saas-coach-scoping',
    notes: 'The policies still say "is a coach" rather than "owns this client". They do not bite today because the dashboard uses the service role, which bypasses them, and that is exactly why they should be right before anyone else is invited.',
  },
  {
    id: 'saas-coach-signup',
    title: 'A coach can be set up without Kade doing it by hand',
    description: 'Invitation, first-run setup, their own details.',
    status: 'planned',
    effort: 'M',
    blockedBy: 'saas-coach-scoping',
    notes: 'Today a coach is created by hand. The pilot can survive that for ten. Nothing beyond ten can.',
  },
  {
    id: 'saas-doctrine-enforcement',
    title: 'The highest-consequence doctrine rules enforced in code',
    description: 'Checks that refuse, rather than paragraphs that ask.',
    status: 'planned',
    effort: 'L',
    notes: 'The licensing blocker named in the auto-memory: the rules live in prompt text and the code rarely checks the output. With his own clients Kade is the safety net. With other people\'s clients he is not.',
  },
  {
    id: 'saas-licence-agreement',
    title: 'Coach and gym licence terms',
    description: 'Who holds the data, scope of practice, screening, insurance, termination.',
    status: 'blocked',
    effort: 'M',
    notes: 'Waits on the lawyer. Questions 5, 22 and 33 of the brief. A pilot can run under a short agreement before the full terms exist.',
  },
  {
    id: 'saas-pilot-agreement',
    title: 'The pilot agreement and the first ten coaches',
    description: '90 days, free, in exchange for data rights and structured reviews.',
    status: 'planned',
    effort: 'S',
    notes: 'Free rather than cheap, so it attracts commitment and sets no price anchor. The list of ten, with why each one, is Kade\'s.',
  },
  {
    id: 'saas-pricing-decision',
    title: 'Pricing decided from what the pilot says',
    description: 'Per active client, per read, or tiers.',
    status: 'planned',
    effort: 'S',
    blockedBy: 'saas-pilot-agreement',
    notes: 'Cost is not the constraint: about $1.18 per client for their whole coaching lifetime, measured. Tiers gated on how many clients are being read, inside the $50-250/month band coaching software already sits in. NOT per active client, which is Collective language and must never appear in Body Recode SaaS material. Solo coaches are proof; premium clubs are the business (~35 at $1,200 beats ~230 solo at $180).',
  },
  {
    id: 'saas-coach-billing',
    title: 'Coaches can be charged',
    description: 'Subscription or per-client billing on top of the existing payment routing.',
    status: 'planned',
    effort: 'M',
    blockedBy: 'saas-pricing-decision',
    notes: 'Per-tenant payment routing and a partner charging model already exist at version 1. This is connecting them to a price, not building billing.',
  },
  {
    id: 'saas-support-loop',
    title: 'A way for a coach to report something wrong, and be answered',
    description: 'And the 30, 60 and 90 day reviews that make the pilot worth running.',
    status: 'planned',
    effort: 'S',
    notes: 'A pilot with no structured feedback is free usage. This is the part that turns coaches into evidence.',
  },
  {
    id: 'saas-client-data-rights',
    title: 'Export and delete a client\'s information on request',
    description: 'What the privacy policy promises, as a thing a coach can actually do.',
    status: 'planned',
    effort: 'M',
    notes: 'The policy says a person can ask to see what we hold, correct it, or have it deleted, answered within 30 days. Today that is a person with database access doing it by hand.',
  },
  {
    id: 'saas-monitoring',
    title: 'Know when it breaks before a coach tells you',
    description: 'Error alerting, failed job alerts, and a restore test.',
    status: 'planned',
    effort: 'M',
    notes: 'With his own clients Kade notices. With other people\'s clients, silence is not safety. Includes proving a backup can actually be restored, which has never been tested.',
  },
  {
    id: 'saas-evidence-pack',
    title: 'The evidence pack for club conversations',
    description: 'What the pilot produced, in a form a gym owner reads.',
    status: 'planned',
    effort: 'S',
    blockedBy: 'saas-support-loop',
    notes: 'The reason the pilot exists. Solo coaches are proof; the business is clubs, and evidence is what makes that conversation short.',
  },

  {
    id: 'saas-copilot-for-coaches',
    title: 'The co-pilot works for a coach, on their own clients',
    description: 'Opened past the owner allowlist, and scoped so the roster it sees is theirs.',
    status: 'shipped',
    shippedAt: '2026-09-17',
    effort: 'M',
    surfaces: ['src/app/api/copilot/route.ts', 'src/app/api/clients/[id]/copilot/route.ts', 'src/lib/roster-next-actions.ts'],
    notes: 'Kade: the co-pilot belongs in the pilot. It was gated to his email alone, so a second coach got a refusal, and the practice-wide roster it reads was unscoped, so opening it naively would have handed one coach every client in the system. Now any coach may use it, and what it sees is their own roster and their own clients.',
  },
  {
    id: 'saas-copilot-limits',
    title: 'Limits on what the co-pilot costs and can do for a coach',
    description: 'Per-coach usage caps, and a decision on which tools it may run.',
    status: 'shipped',
    shippedAt: '2026-09-17',
    effort: 'S',
    surfaces: ['src/lib/copilot-limits.ts', 'sql/2026-09-17_copilot_usage.sql'],
    notes: '150 messages per Brisbane day for a coach who is not the owner, across both co-pilots, counted before generating so a refused message costs nothing. Adjustable by environment setting. The refusal is friendly and says the limit resets at midnight. Decision made on actions: a pilot coach\'s co-pilot ANSWERS, it does not act. The two routes that edit a nutrition plan or a reading draft stay owner-only until doctrine enforcement lands, and the code now says why.',
  },

  /* ── Evidence: the research passes that gate go-live ─────────────────── */
  {
    id: 'research-g1-regulatory',
    title: 'Regulatory research and the lawyer brief',
    description: 'Medical device status, advertising, privacy, scope of practice.',
    status: 'in_progress',
    effort: 'M',
    surfaces: ['00_PLAYBOOK/research_briefs/2026-09-17_LAWYER_BRIEF.pdf'],
    notes: 'Both research chats run and verified against the primary instruments. 33 questions ready. Waiting on Kade to book the lawyer, and on the Anthropic sales conversation about zero data retention.',
  },
  {
    id: 'research-e1-electrolytes',
    title: 'Electrolytes, fluid and minerals',
    description: 'Nine unsourced statements the system already makes, and 24 practitioner claims to test.',
    status: 'planned',
    effort: 'M',
    notes: 'Briefed 15 Sep, two chats. Includes whether "electrolytes on waking", the sauna advice and the salt cravings question earn their place.',
  },
  {
    id: 'research-r2-recovery',
    title: 'The 22 recovery protocols with no research behind them',
    description: 'Heat, cold, contrast and devices, breathwork and load.',
    status: 'planned',
    effort: 'L',
    notes: 'Briefed 16 Sep, four chats. These are prescribed to clients today. 12 of the 34 protocols are already researched; these are the rest.',
  },
  {
    id: 'research-s1-screening',
    title: 'Screening someone before they start training',
    description: 'The Australian standard, and who software may clear.',
    status: 'planned',
    effort: 'S',
    notes: 'Briefed 16 Sep. Partly answered already: the privacy research handed over the six standard pre-exercise questions. Also unblocks the starting-from-zero product.',
  },
  {
    id: 'research-p1-engine-rules',
    title: 'The training and nutrition rules the engine runs on',
    description: '13 training rules and 11 nutrition rules, checked as written.',
    status: 'planned',
    effort: 'L',
    notes: 'Briefed 16 Sep, two chats. These rules decide what a real person is told to do and have never been checked against the literature the way the interpretation method has.',
  },
  {
    id: 'research-m1-measurement',
    title: 'Telling real change from noise',
    description: 'Scale swings, tape error, self-report reliability, and the threshold for acting.',
    status: 'planned',
    effort: 'M',
    notes: 'Briefed 16 Sep. Everything downstream depends on distinguishing a real change from measurement error, and none of the current thresholds came from measurement research.',
  },
  {
    id: 'research-findings-doc',
    title: 'One document of everything the research found',
    description: 'Decisions first, then each pass, regulatory separate, then what is still open.',
    status: 'planned',
    effort: 'M',
    blockedBy: 'research-m1-measurement',
    notes: 'Kade asked for this on 17 Sep. Each section is written as its pass lands, so the final build is assembly rather than recall.',
  },
]
