import type { Step } from './buildout-types'

/**
 * BODY RECODE SAAS: the coach platform, and what has to be true before it is
 * sold to anyone.
 *
 * Added 17 September 2026, when the order changed: Body Recode SaaS goes to
 * market first, Strenn follows. Everything here is either done this week or
 * blocks the pilot. Plan and reasoning:
 * `06_SAAS_PLATFORM_BUILD/2026-09-17_Coach_SaaS_Pilot_Plan.md`.
 *
 * Steps live here once. `build-sequence.ts` arranges them into the board's
 * stages by id and tags them with the products they serve.
 */
export const COACH_SAAS_STEPS: Step[] = [
  /* ── Shipped: safety and privacy work, 16 to 17 September ───────────── */
  {
    id: 'saas-coach-scoping',
    title: 'A coach sees only their own clients',
    description: 'Ownership enforced at four layers, with a test that proves it.',
    status: 'shipped',
    shippedAt: '2026-09-17',
    effort: 'L',
    commits: ['e97d9edc'],
    surfaces: ['src/lib/coach-scope.ts', 'src/middleware.ts', 'src/app/dashboard/layout.tsx', 'scripts/test-coach-scope.ts'],
    notes: 'THE blocker. Access was decided by "are you a coach", never "is this your client": 48 dashboard files read clients with no coach filter, on the service-role connection which bypasses row level security. Harmless with one coach, a notifiable breach with two. Now: dashboard requires a coach, the client record layout asserts ownership (covering every page under it), middleware gates all 49 client API routes, lists filter by owner. Verified live.',
  },
  {
    id: 'saas-blood-read-paused',
    title: 'Client-facing blood read switched off',
    description: 'The single feature most likely to make us a medical device, behind a flag.',
    status: 'shipped',
    shippedAt: '2026-09-17',
    effort: 'S',
    commits: ['03ddccc0'],
    surfaces: ['src/lib/blood-read-gate.ts'],
    notes: 'The TGA illustrates "information requiring a health professional" with a consumer interpreting inflammatory markers in their blood. Transcription, GP flags, coach analysis and plan influence all still run. One environment setting reverses it once the lawyer answers.',
  },
  {
    id: 'saas-consent-at-collection',
    title: 'Consent asked where health information is collected',
    description: 'A notice and an unticked box on the intake and the blood upload, both timestamped.',
    status: 'shipped',
    shippedAt: '2026-09-17',
    effort: 'M',
    commits: ['f5d6c2be'],
    surfaces: ['src/components/collection-notice.tsx', 'sql/2026-09-17_intake_health_consent.sql'],
    notes: 'Sensitive information needs consent that is specific and not bundled, and the notice has to be given at or before collection, including which countries data goes to. A footer link is neither. Consent is stored, because a tick nobody recorded is the same as no tick.',
  },
  {
    id: 'saas-privacy-policy-rewrite',
    title: 'Privacy policy rewritten and published',
    description: 'Health information listed, every provider\'s country named, automated decisions and retention sections added.',
    status: 'shipped',
    shippedAt: '2026-09-17',
    effort: 'M',
    commits: ['68599288', '713b37c4'],
    surfaces: ['src/app/privacy/page.tsx', '11_SECURITY_AND_COMPLIANCE/07_PRIVACY_POLICY.pdf'],
    notes: 'The automated decisions section becomes a legal requirement on 10 December 2026 and is in early. Record copy filed as a PDF. Draft pending the lawyer.',
  },
  {
    id: 'saas-pixel-off-client-pages',
    title: 'Advertising pixel kept off client pages',
    description: 'It was firing on the intake, portal, blood upload and check-in.',
    status: 'shipped',
    shippedAt: '2026-09-17',
    effort: 'S',
    commits: ['8d171826'],
    surfaces: ['src/components/meta-pixel.tsx'],
    notes: 'A pixel page view sends the page and referring address to Meta, and those addresses carry a client\'s private access token. The policy promised Meta receives no health information; this makes that true. Purchase tracking untouched.',
  },
  {
    id: 'saas-adults-only',
    title: 'Under 18s blocked at both entry points',
    description: 'The scorecard stops, and the intake refuses at the server.',
    status: 'shipped',
    shippedAt: '2026-09-17',
    effort: 'S',
    commits: ['0cea8c7', '76cb57a4'],
    notes: 'Open item on the peer review control sheet. Reading where a developing body holds fat risks feeding disordered eating, and the doctrine exclusions were written for adults. What a safeguarded youth version would need still waits on clinical input.',
  },
  {
    id: 'saas-retention-seven-years',
    title: 'Retention set to seven years, and the existing six re-derived',
    description: 'Code and the published promise now agree.',
    status: 'shipped',
    shippedAt: '2026-09-17',
    effort: 'S',
    commits: ['59469b86'],
    notes: 'State health records law requires seven years from last service for adult health records. Nothing is deleted by the number: it decides when a record becomes eligible, and deletion stays a deliberate act.',
  },
  {
    id: 'saas-breach-plan',
    title: 'Breach response plan',
    description: 'Contain, assess, notify, review, with a first-hour checklist.',
    status: 'shipped',
    shippedAt: '2026-09-17',
    effort: 'S',
    surfaces: ['11_SECURITY_AND_COMPLIANCE/08_BREACH_RESPONSE_PLAN.pdf'],
    notes: 'Written to be followed by one person under pressure. States what is not yet true: no insurance, no licensee breach terms, never tested.',
  },
  {
    id: 'saas-processor-register',
    title: 'Data processors verified, and what sits outside the system',
    description: 'Every provider, its country, and the Dropbox and email copies the platform cannot reach.',
    status: 'shipped',
    shippedAt: '2026-09-17',
    effort: 'M',
    surfaces: ['11_SECURITY_AND_COMPLIANCE/04_DATA_PROCESSORS.md', '11_SECURITY_AND_COMPLIANCE/09_RECORDS_OUTSIDE_THE_SYSTEM.md'],
    notes: 'Supabase confirmed in Sydney. Zoom records nothing and its credentials are write-only. 46 shared links audited, none touching client data. Five client folders in Dropbox hold health documents outside the retention rule.',
  },

  /* ── Before a second coach signs in ──────────────────────────────────── */
  {
    id: 'saas-rls-alignment',
    title: 'Database policies match the ownership model',
    description: 'The second layer behind the service-role connection.',
    status: 'shipped',
    effort: 'M',
    blockedBy: 'saas-coach-scoping',
    notes: 'DONE 19 Sep. Seven rules said "is a coach" rather than "owns this client", and the coach check is only "do you have at least one client", so a second coach with one client would have satisfied it. Invitations (which hold the invite token), feedback and scorecard reports are now scoped through the client or lead to the owning coach; co-pilot preferences to the signed-in email; three server-only tables lost their browser rule. Proved by creating a second coach inside a rolled-back transaction: they saw their own client and nothing else. The same audit found five tables open to the public key and closed them, and found that the server had no permission on the preferences table, so co-pilot preferences had never saved.',
  },
  {
    id: 'saas-coach-signup',
    title: 'A coach can be set up without Kade doing it by hand',
    description: 'Invitation, first-run setup, their own details, and their existing clients.',
    status: 'shipped',
    effort: 'M',
    blockedBy: 'saas-coach-scoping',
    notes: 'DONE 19 Sep. Business > Coaches sends an invitation that works once and lasts 14 days; the coach sets their own password, and their account and configuration are created together so a half-failure leaves a working link rather than a locked-out person. Kade never types anyone else\'s password again. ALSO BUILT, from Kade\'s question about a coach joining with 30 clients: Clients > Import a list, a paste box with a dry run that writes nothing, skips anyone already on that coach\'s list, and optionally emails every new client their intake. A coach never enters client details anyway, only a name and an email, because the rest comes from the client\'s own intake.',
  },
  {
    id: 'saas-doctrine-enforcement',
    title: 'The highest-consequence doctrine rules enforced in code',
    description: 'Checks that refuse, rather than paragraphs that ask.',
    status: 'planned',
    effort: 'L',
    notes: 'The licensing blocker named in the auto-memory: the rules live in prompt text and the code rarely checks the output. With his own clients Kade is the safety net. With other people\'s clients he is not.',
  },
  {
    id: 'saas-licence-agreement',
    title: 'Coach and gym licence terms',
    description: 'Who holds the data, scope of practice, screening, insurance, termination.',
    status: 'blocked',
    effort: 'M',
    notes: 'Waits on the lawyer. Questions 5, 22 and 33 of the brief. A pilot can run under a short agreement before the full terms exist.',
  },
  {
    id: 'saas-pilot-agreement',
    title: 'The pilot agreement and the first ten coaches',
    description: '90 days, free, in exchange for data rights and structured reviews.',
    status: 'in_progress',
    effort: 'S',
    surfaces: ['11_SECURITY_AND_COMPLIANCE/legal/BR_COACH_PILOT_AGREEMENT_v0.1.md', '06_SAAS_PLATFORM_BUILD/2026-09-20_The_First_Five_Coaches.md'],
    notes: 'DRAFTED 20 Sep, not sent. Free rather than cheap, so it attracts commitment and sets no price anchor. Five rather than ten: fewer is one coach\'s opinion, more is a support job. The agreement is written and three of its clauses are marked for the lawyer, because they depend on questions 5, 22 and 33 in the brief. Conversations can happen now; nobody\'s client information goes in until it is signed. The recruiting document exists too, and its finding is the uncomfortable one: ONE application in two months, 59 days unactioned, so the coaches have to be gone and got rather than waited for.',
  },
  {
    id: 'saas-pricing-decision',
    title: 'Pricing decided from what the pilot says',
    description: 'Per active client, per read, or tiers.',
    status: 'planned',
    effort: 'S',
    blockedBy: 'saas-pilot-agreement',
    notes: 'Cost is not the constraint: about $1.18 per client per read cycle (~12 weeks), measured, so under $5 per client per year. Tiers gated on how many clients are being read, inside the $50-250/month band coaching software already sits in. NOT per active client, which is Collective language and must never appear in Body Recode SaaS material. Solo coaches are proof; premium clubs are the business (~35 at $1,200 beats ~230 solo at $180).',
  },
  {
    id: 'saas-coach-billing',
    title: 'Coaches can be charged',
    description: 'Subscription or per-client billing on top of the existing payment routing.',
    status: 'planned',
    effort: 'M',
    blockedBy: 'saas-pricing-decision',
    notes: 'Per-tenant payment routing and a partner charging model already exist at version 1. This is connecting them to a price, not building billing.',
  },
  {
    id: 'saas-support-loop',
    title: 'A way for a coach to report something wrong, and be answered',
    description: 'And the 30, 60 and 90 day reviews that make the pilot worth running.',
    status: 'shipped',
    effort: 'S',
    notes: 'ALREADY BUILT, confirmed 20 Sep 2026 by following the path end to end rather than trusting this board. A support button sits on every dashboard page; a coach files a ticket with the page they were on; it lands in Kade\'s inbox; setting a status with a note emails the coach the status AND the note. So "report something wrong and be answered" works today. The board said planned because nobody went back and changed it after the support work shipped in July. The structured part of the feedback is the 30/60/90 reviews and the eleven-point list of what to test, both in the first-five-coaches document.',
  },
  {
    id: 'saas-client-data-rights',
    title: 'Export and delete a client\'s information on request',
    description: 'What the privacy policy promises, as a thing a coach can actually do.',
    status: 'in_progress',
    effort: 'M',
    notes: 'BUILT 20 Sep, as a command Kade runs rather than a button a coach presses, which is the right shape for a pilot where the agreement says the coach asks and we do it. The export that existed covered SEVEN tables; sixty-four hold a client\'s information. The table list is now asked of the database every time rather than written down, because a written list is exactly how the seven-table version happened. Two hops: rows pointing at the client, then rows hanging off those with no client link of their own. Deletion goes deepest first and the client row last, explicitly rather than by cascade, since some references are set to null and that leaves her information in a row that no longer says whose it is. Also removes her uploaded files, and her name where a saved report quoted it rather than referencing her by id, which no amount of walking the database would find. Dry run by default. Proven on live data: 420 records across 29 places for an active client, 166 records and 5 files for a former one. STILL OPEN: a coach-facing button, and the fact that backups are not touched, which needs the pruning schedule.',
  },
  {
    id: 'saas-monitoring',
    title: 'Know when it breaks before a coach tells you',
    description: 'Error alerting, failed job alerts, and a restore test.',
    status: 'shipped',
    effort: 'M',
    notes: 'DONE 20 Sep, in three pieces. Generation failures a coach actually saw are recorded with what the coach was told, and emailed immediately when the coach is not Kade. Every scheduled job now records its run, and a failure emails at the time with a six-hour quiet window per job so one broken job is one email rather than six a day. Every background function is covered by a single listener, which also covers any added later. The daily health check reports all of it plus the age of the last backup, and, more importantly, names any job that has NOT run inside its own window, which is the only way a job that silently stopped being scheduled is ever visible. Deliberate: an unauthorised knock is not recorded as a run, and recording never throws, so monitoring cannot become the outage. 16 tests.',
  },
  {
    id: 'saas-evidence-pack',
    title: 'The evidence pack for club conversations',
    description: 'What the pilot produced, in a form a gym owner reads.',
    status: 'planned',
    effort: 'S',
    blockedBy: 'saas-support-loop',
    notes: 'The reason the pilot exists. Solo coaches are proof; the business is clubs, and evidence is what makes that conversation short.',
  },

  {
    id: 'saas-copilot-for-coaches',
    title: 'The co-pilot works for a coach, on their own clients',
    description: 'Opened past the owner allowlist, and scoped so the roster it sees is theirs.',
    status: 'shipped',
    shippedAt: '2026-09-17',
    effort: 'M',
    surfaces: ['src/app/api/copilot/route.ts', 'src/app/api/clients/[id]/copilot/route.ts', 'src/lib/roster-next-actions.ts'],
    notes: 'Kade: the co-pilot belongs in the pilot. It was gated to his email alone, so a second coach got a refusal, and the practice-wide roster it reads was unscoped, so opening it naively would have handed one coach every client in the system. Now any coach may use it, and what it sees is their own roster and their own clients.',
  },
  {
    id: 'saas-copilot-limits',
    title: 'Limits on what the co-pilot costs and can do for a coach',
    description: 'Per-coach usage caps, and a decision on which tools it may run.',
    status: 'shipped',
    shippedAt: '2026-09-17',
    effort: 'S',
    surfaces: ['src/lib/copilot-limits.ts', 'sql/2026-09-17_copilot_usage.sql'],
    notes: '150 messages per Brisbane day for a coach who is not the owner, across both co-pilots, counted before generating so a refused message costs nothing. Adjustable by environment setting. The refusal is friendly and says the limit resets at midnight. Decision made on actions: a pilot coach\'s co-pilot ANSWERS, it does not act. The two routes that edit a nutrition plan or a reading draft stay owner-only until doctrine enforcement lands, and the code now says why.',
  },

  /* ── Capture: the measurement has to come from somewhere ─────────────── */
  {
    id: 'capture-scan-vendor',
    title: 'Pick a phone body scan to integrate',
    description: 'Vendors and pricing researched. Deferred until the pilot is close.',
    status: 'deferred',
    effort: 'S',
    surfaces: ['06_SAAS_PLATFORM_BUILD/2026-09-17_Capture_Scan_and_Wearables.md'],
    notes: 'Kade, 17 Sep: most clubs do NOT have a body composition machine, so capture has to ship inside the product. Integrate, never build: a phone scanner is a computer vision company. DEFERRED 17 Sep 2026: not close enough to a pilot, and every vendor starts a monthly bill on signature. Research is banked so nobody repeats it. Prism Labs fits best (from $500/mo, from $2 per ACTIVE user, unlimited scans, inactive months free, so about $4 per client per year, plus a free 90-day sandbox and an existing ROOK wearable connection). 3DLOOK has the best published accuracy (repeatability under 1cm) but a $499-1,000/mo floor. Size Stream is SOC 2 Type 2, price unknown. Trigger to restart: coaches are using the platform and the re-read is the next thing blocking the subscription argument.',
  },
  {
    id: 'capture-scan-competence-rule',
    title: 'What a scan is allowed to say',
    description: 'Authoritative for change and distribution. Never for absolute body fat.',
    status: 'planned',
    effort: 'S',
    blockedBy: 'capture-scan-vendor',
    notes: 'Published work is consistent: phone scans are good at group level and imprecise for one person\'s absolute numbers, but scan-to-scan repeatability is under a centimetre, better than a human with a tape. We need direction of change over twelve weeks, not a body fat percentage. The rule goes into doctrine BEFORE the first scan lands, not after a client is quoted a number that contradicts her mirror.',
  },
  {
    id: 'capture-scan-integration',
    title: 'The scan in the portal and in the re-read',
    description: 'She scans on a Sunday in her bedroom and the numbers arrive.',
    status: 'planned',
    effort: 'M',
    blockedBy: 'capture-scan-competence-rule',
    notes: 'The point of the whole thing. Almost every baseline held is week one, with one re-capture across six clients, because re-doing a tape measure and three photographs is a chore nobody does. Consent wording, retention and the privacy policy need updating first: a 3D body model is closer to biometric information than a tape measurement.',
  },
  {
    id: 'capture-wearables-aggregator',
    title: 'Device data through one aggregator, not four integrations',
    description: 'Sleep and heart rate variability into the slot the engine already has.',
    status: 'planned',
    effort: 'M',
    notes: 'Do not integrate Whoop, Oura, Garmin and Apple Health separately. ROOK is the obvious aggregator and is already connected to one of the scan vendors. The receiver already exists; this is the feed.',
  },

  /* ── Evidence: the research passes that gate go-live ─────────────────── */
  {
    id: 'research-g1-regulatory',
    title: 'Regulatory research and the lawyer brief',
    description: 'Medical device status, advertising, privacy, scope of practice.',
    status: 'in_progress',
    effort: 'M',
    surfaces: ['00_PLAYBOOK/research_briefs/2026-09-17_LAWYER_BRIEF.pdf'],
    notes: 'Both research chats run and verified against the primary instruments. 33 questions ready. Waiting on Kade to book the lawyer, and on the Anthropic sales conversation about zero data retention.',
  },
  {
    id: 'research-e1-electrolytes',
    title: 'Electrolytes, fluid and minerals',
    description: 'Nine unsourced statements the system already makes, and 24 practitioner claims to test.',
    status: 'shipped',
    effort: 'M',
    notes: 'DONE 19 Sep. Both chats run, verified at PubMed (22 identifiers, all correct, no fabrications) and applied. E1a fixed the blood pressure medicine rule that was backwards for the potassium-holding classes, the salt craving question, the water target, electrolytes as a daily habit and the sauna gates. E1b added the contest prep refusal, the heat and long-session wording, 12 lifter and competitor referrals, and 18 intake questions gated so a non-competitor only sees 11 of them. Intake is now 271 questions. Still open: most of the general referral list is documentation rather than something the system fires by itself, because it depends on events rather than intake answers.',
  },
  {
    id: 'research-r2-recovery',
    title: 'The 22 recovery protocols with no research behind them',
    description: 'Heat, cold, contrast and devices, breathwork and load.',
    status: 'shipped',
    effort: 'L',
    notes: 'DONE 20 Sep. Four chats plus a summary, 79 identifiers verified at PubMed across the first three groups, all correct. The protocols were mostly fine; the claims attached to them were not. Red light was pulled outright. Heat gained alcohol as a hard contraindication, cold gained an honest evidence gap and a breath-hold water rule, and the device claims that named a mechanism were rewritten. 33 protocols remain in the library.',
  },
  {
    id: 'research-s1-screening',
    title: 'Screening someone before they start training',
    description: 'The Australian standard, and who software may clear.',
    status: 'planned',
    effort: 'S',
    notes: 'Briefed 16 Sep. Partly answered already: the privacy research handed over the six standard pre-exercise questions. Also unblocks the starting-from-zero product.',
  },
  {
    id: 'research-p1-engine-rules',
    title: 'The training and nutrition rules the engine runs on',
    description: '13 training rules and 11 nutrition rules, checked as written.',
    status: 'planned',
    effort: 'L',
    notes: 'Briefed 16 Sep, two chats. These rules decide what a real person is told to do and have never been checked against the literature the way the interpretation method has.',
  },
  {
    id: 'research-m1-measurement',
    title: 'Telling real change from noise',
    description: 'Scale swings, tape error, self-report reliability, and the threshold for acting.',
    status: 'planned',
    effort: 'M',
    notes: 'Briefed 16 Sep. Everything downstream depends on distinguishing a real change from measurement error, and none of the current thresholds came from measurement research.',
  },
  {
    id: 'research-i1-iron',
    title: 'Iron and ferritin in menstruating women',
    description: 'The pattern the engine would have read as stress every single time.',
    status: 'shipped',
    effort: 'M',
    notes: 'DONE 20 Sep, 49 identifiers verified. Structural, not verbal: the four patterns are exhaustive, so a cause the model does not recognise is absorbed into the nearest one rather than dropped. The engine may no longer name a pattern at all while that cluster plus any blood-loss answer is present, until she records that she has seen a doctor. Five tiered questions added. In the trials, the placebo groups reported fatigue falling 13 and 28.8 per cent, so feeling better at week four proves nothing.',
  },
  {
    id: 'research-t1-thyroid',
    title: 'Thyroid, especially the subclinical kind',
    description: 'Why the engine must not cut her food further while this is unchecked.',
    status: 'shipped',
    effort: 'M',
    notes: 'DONE 20 Sep, 68 identifiers verified. A questionnaire cannot give a likelihood here, so it never tries. The important consequence is that the engine builds deficits, and when weight will not move its natural next step is to cut harder, which is exactly wrong if a thyroid is the reason. It is now barred from deepening a deficit while the flag is open, and the strongest argument is measurement: cutting before the test shifts the test.',
  },
  {
    id: 'research-b1-bone',
    title: 'What actually builds bone in women 35 to 60',
    description: 'The hole we made ourselves when the vibration plate claim was pulled.',
    status: 'shipped',
    effort: 'M',
    notes: 'DONE 20 Sep, 88 identifiers verified, and the pass corrected one of its own wrong titles mid-draft. Heavy barbell work plus impact IS the prescription rather than an option, so for a woman at risk the barbell is not negotiable. No exercise trial has ever shown fracture prevention, and we say so instead of implying it.',
  },
  {
    id: 'research-findings-doc',
    title: 'One document of everything the research found',
    description: 'Organised by how things went wrong, not by which pass found it.',
    status: 'shipped',
    effort: 'M',
    surfaces: ['00_PLAYBOOK/2026-09-20_WHAT_THE_RESEARCH_FOUND.md'],
    notes: 'DONE 20 Sep, v2, written and rebuilt after the headline number was counted rather than claimed: 48 statements verified as shipped before the research began, 47 removed, 1 relabelled. An audit script re-runs the count against the last commit before the research started, so the figure answers for itself. Covers the nine passes run so far and NOT the three still open (screening, engine rules, measurement noise), so it wants a second edition when those land.',
  },
]
