import type { Step } from './buildout-types'

/**
 * Rey's own build steps: the things only Rey needs.
 *
 * Rey is the consumer product built on the Body Recode read and the coaching
 * engine (spec: Dropbox 05_REY/2026-09-13_REY_Product_Specification_v2.0.md).
 * Most of what Rey depends on is NOT here, because it is shared work and
 * already lives on the read or engine manifests. Duplicating it here would let
 * the same step exist twice and disagree.
 *
 * This file is storage, not a board. The Build board (build-sequence.ts)
 * arranges these steps, together with the read and engine steps, into the
 * order they are actually built. Update a step's status HERE.
 *
 * Section numbers in notes refer to the Rey specification.
 *
 * Added 14 Sep 2026.
 */
export const REY_STEPS: Step[] = [
  /* ── Decided ─────────────────────────────────────────────── */
  {
    id: 'rey-origin-recovered',
    title: 'The 2024 origin recovered',
    description: 'The original November 2024 Rey concept reconstructed and filed, so the later narrowing is visible.',
    status: 'shipped',
    shippedAt: '2026-09-13',
    effort: 'S',
    surfaces: ['Dropbox 05_REY/2026-09-13_REY_Origin_Recovered_2024.md'],
    notes: 'A recollection reconstructed from ChatGPT context, not a primary document. Older business plans or specs from the WeThrive period may still exist elsewhere.',
  },
  {
    id: 'rey-spec',
    title: 'The product specification',
    description: 'The whole product decided: audience, pricing, the session, first run, the loop, when it goes wrong, the re-read and housekeeping.',
    status: 'shipped',
    shippedAt: '2026-09-14',
    effort: 'M',
    surfaces: ['Dropbox 05_REY/2026-09-13_REY_Product_Specification_v2.0.md'],
    notes: 'Supersedes the two April 2026 documents, which had Rey as a delivery layer. Rey is now the whole product. The spec grows by section and is never rewritten.',
  },

  /* ── Stage 1: Rey on the web ─────────────────────────────── */
  {
    id: 'rey-consumer-read',
    title: 'The consumer read',
    description: 'The read written for her rather than for a coach. Same classification, same constraints, different writing.',
    status: 'planned',
    effort: 'L',
    notes: 'Kade\'s work, with writing support. Not a translation job: the existing read assumes the reader knows the doctrine. Keeps the two sections that define the product, what this does not mean and what is most commonly misread. Spec 4.3.',
  },
  {
    id: 'rey-progressive-intake',
    title: 'Progressive intake',
    description: '30 to 40 questions up front for a defensible read in about fifteen minutes, the rest asked by Rey across her first weeks.',
    status: 'planned',
    effort: 'M',
    blockedBy: 'minimum-question-set',
    notes: 'Decided 14 Sep. The read deepens the longer she stays, which turns data collection into retention. Blocked on choosing the question set, which is doctrinal. Spec 11.7.',
  },
  {
    id: 'rey-signup-subscription',
    title: 'Signup, trial and subscription',
    description: 'Seven-day trial with a card upfront, $199 a year or $29 a month chosen at signup, a reminder on day five.',
    status: 'planned',
    effort: 'M',
    notes: 'On the WEB, not in the app, so the subscription stays outside the app stores (Apple takes 15 to 30 percent). The app is only for training. Spec 3 and 11.1 to 11.2.',
  },
  {
    id: 'rey-plan-on-screen',
    title: 'Training and nutrition guidance on screen',
    description: 'Her plan shown on screen, with nutrition as targets and direction rather than a menu.',
    status: 'planned',
    effort: 'M',
    notes: 'Voice is for talking about the plan, not narrating it. Full meal plans sit behind an evidence gate (see Later). Spec 4.6.',
  },
  {
    id: 'rey-weekly-checkin',
    title: 'Weekly check-in',
    description: 'A short check-in on a day she chooses. Typed on the web first, voice when the app exists.',
    status: 'planned',
    effort: 'S',
    notes: 'Mostly built for coaching clients. She never logs a meal: one question, roughly on plan, a bit off, or off the rails. Spec 12.1 and 12.3.',
  },
  {
    id: 'rey-progress-view',
    title: 'What progress she sees',
    description: 'Sleep, readiness, symptoms, strength and measurements lead. Scale weight available, never the headline.',
    status: 'planned',
    effort: 'M',
    notes: 'For a woman in perimenopause the scale is the most misleading number she owns and the one most likely to make her quit. Spec 12.4.',
  },
  {
    id: 'rey-reread-moment',
    title: 'The re-read as a moment',
    description: 'Flagged a week ahead, a ten-minute re-ask, and a read with a before and after.',
    status: 'planned',
    effort: 'M',
    blockedBy: 'reread-generator',
    notes: 'Says what did NOT move as well as what did. Week 48 for annual subscribers is the story of her year, four weeks before renewal. Spec 14.',
  },
  {
    id: 'rey-consent-privacy',
    title: 'Tiered consent and the privacy policy',
    description: 'Run and improve Rey required; research and trial invitations her choice; her data never sold.',
    status: 'planned',
    effort: 'M',
    notes: 'A lawyer reviews it before launch. Consent cannot be retrofitted onto existing users, so this must be right on day one. Includes the clause that data moves with the business under the same promises if it is acquired. Spec 15.4 to 15.6.',
  },
  {
    id: 'rey-coachless-position',
    title: 'The position on running with no coach',
    description: 'A formal clinical and liability position, and insurance, for a product where nobody reviews what Rey tells her.',
    status: 'planned',
    effort: 'M',
    notes: 'A lawyer\'s work. Required before anyone pays.',
  },
  {
    id: 'rey-cancel-pause-delete',
    title: 'Cancel, refund, pause and delete',
    description: 'One-tap cancel, fourteen-day annual refund, pause for up to three months, download and delete everything.',
    status: 'planned',
    effort: 'S',
    notes: 'Pregnancy pauses her subscription at no cost. Spec 13.6, 13.8, 15.1 to 15.3.',
  },
  {
    id: 'rey-name-voice',
    title: 'Rey\'s name and voice',
    description: 'The actual name and the actual voice. Female, warm but direct is already decided.',
    status: 'planned',
    effort: 'S',
    notes: 'Brand decision, Kade\'s call. Governs every line Rey says. A synthetic voice needs a licence for commercial use, and a voice modelled on a real person needs that person\'s written consent. Spec 10.1.',
  },

  /* ── Stage 2: Rey in her ear ─────────────────────────────── */
  {
    id: 'rey-phone-app',
    title: 'The phone app',
    description: 'A real app, because headphone audio that keeps playing with the screen off cannot be a website.',
    status: 'planned',
    effort: 'L',
    notes: 'New territory. She signs in with the account created on the web.',
  },
  {
    id: 'rey-voice',
    title: 'Real-time voice',
    description: 'Speech in, understanding, speech out, fast enough to feel like a conversation in a noisy gym.',
    status: 'planned',
    effort: 'L',
    notes: 'The genuinely new capability. Making a working version is within reach; making it good under interruptions, gym noise and a phone in a pocket is where the effort goes. Spec 6.',
  },
  {
    id: 'rey-session-flow',
    title: 'The guided session',
    description: 'Warm-up, each exercise introduced with one cue, tempo called, effort asked as easy, about right or hard, rest timed, logged from the conversation.',
    status: 'planned',
    effort: 'M',
    notes: 'Rey paces tempo rather than counting reps, because it cannot see her. Spec 10.5 to 10.10.',
  },
  {
    id: 'rey-override-rules',
    title: 'When she can overrule Rey',
    description: 'Amber: yes, with a warning. Red: no, and Rey explains why. Pain stops the exercise immediately.',
    status: 'planned',
    effort: 'S',
    blockedBy: 'session-readiness-adapts',
    notes: 'A prescribed rest day counts as completing the plan and never breaks a streak. Spec 10.4, 10.7 and 10.8.',
  },
  {
    id: 'rey-music-ducking',
    title: 'Music ducking',
    description: 'Her music lowers when Rey speaks and comes back afterwards, across her own music apps.',
    status: 'planned',
    effort: 'M',
    notes: 'Critical and easy to overlook. If she has to choose between her playlist and her coach, she chooses the playlist. Spec 10.11.',
  },
  {
    id: 'rey-offline-sessions',
    title: 'Offline sessions',
    description: 'The session downloads before it starts and runs with no signal, syncing afterwards.',
    status: 'planned',
    effort: 'M',
    notes: 'Gyms have poor signal. A coach that goes silent mid-set is worse than none. Spec 10.2.',
  },
  {
    id: 'rey-talk-level',
    title: 'Talking level',
    description: 'Chatty, focused or minimal.',
    status: 'planned',
    effort: 'S',
    notes: 'Settles an argument that would otherwise lose half the users either way. Spec 10.11.',
  },
  {
    id: 'rey-first-refusal',
    title: 'The first refusal, planned into week one',
    description: 'Her first week is shaped so she experiences Rey holding a genuine line.',
    status: 'planned',
    effort: 'S',
    notes: 'Must be a real limit her read supports, never invented to make a point. If her first week is all green days she never discovers what makes Rey different. Spec 11.5.',
  },
  {
    id: 'rey-injury-disclosure',
    title: 'Something\'s hurting, one tap away',
    description: 'Reporting pain is the easiest action in the app, and it means adjusting, not stopping everything.',
    status: 'planned',
    effort: 'S',
    blockedBy: 'session-soreness-triage',
    notes: 'Rey cannot see her. If telling Rey feels like it will cost her a month, she will hide it. Anything significant pauses that area and sends her to a physiotherapist or GP. Rey is not a rehabilitation tool. Spec 13.3.',
  },
  {
    id: 'rey-distress-tested',
    title: 'Distress response, tested',
    description: 'Rey recognises distress, suggests her GP for low mood, and gives Lifeline 13 11 14 or 000 in a crisis.',
    status: 'planned',
    effort: 'M',
    notes: 'A responsibility, not a feature. Rey never counsels or diagnoses. Must be proven to work before launch, not assumed. Spec 13.9.',
  },

  /* ── Stage 3: the loop gets smart ────────────────────────── */
  {
    id: 'rey-between-sessions',
    title: 'Rey answers from her read, any time',
    description: 'She asks why she is so tired at nine at night, and Rey answers from her read rather than from the internet.',
    status: 'planned',
    effort: 'L',
    notes: 'The capability no competitor can offer, because none has a read to answer from. When a question is outside her read or belongs with a clinician, Rey says so. Spec 12.7.',
  },
  {
    id: 'rey-notices',
    title: 'Rey notices things',
    description: 'Small weekly observations drawn from her own record.',
    status: 'planned',
    effort: 'M',
    notes: 'Every observation must be real. An invented pattern damages trust in the read itself. Spec 12.8 and 12.9.',
  },
  {
    id: 'rey-rest-day-check',
    title: 'Rest-day voice check: sleep, flushes, mood',
    description: 'An optional twenty-second check on rest days. Where cycle and symptom tracking lives.',
    status: 'planned',
    effort: 'S',
    notes: 'Captures the most valuable signal in the product without feeling like tracking. Spec 12.2.',
  },
  {
    id: 'rey-notifications',
    title: 'Notifications about her body, never engagement',
    description: 'A reminder she set, the weekly check-in, and genuine observations. Nothing else.',
    status: 'planned',
    effort: 'S',
    notes: 'Never "don\'t break your streak". Spec 12.5.',
  },
  {
    id: 'rey-bloodwork',
    title: 'Bloodwork into the read',
    description: 'She photographs a pathology report and the read incorporates it.',
    status: 'planned',
    effort: 'M',
    blockedBy: 'rey-tga-samd-position',
    notes: 'A large differentiator, and the clearest justification for the price over an algorithm. The function most likely to fall outside the wellness software exclusion, so it waits on the regulatory opinion. Blood panel handling already exists in the coaching product; porting it is the work.',
  },
  {
    id: 'rey-clinician-access',
    title: 'Her GP or physio can see her read',
    description: 'Read-only access for a period she chooses, expiring automatically.',
    status: 'planned',
    effort: 'S',
    notes: 'She walks into an appointment with a document. The quiet bridge to practitioners without selling to them. Spec 15.10.',
  },

  /* ── Stage 1: name and demand (added in the 14 Sep gap audit) ── */
  {
    id: 'rey-price-test',
    title: 'Put the price in front of real people first',
    description: 'A page with the offer, $199 a year, and a pre-order or waitlist button, shown to the audience already held.',
    status: 'in_progress',
    effort: 'S',
    surfaces: ['/founding', '/dashboard/saas'],
    notes: 'BUILT 14 Sep: bodyrecode.au/founding, results on the SaaS Launch board. Priestley scorecard method, $199/yr with $29/mo, founding list (no payment). Pass mark set before it ran: 1 in 5 of women who see the price join = go, under 1 in 10 = rethink. Stays in progress until the warm list has been sent to it and 30 women have seen the price. Can start now, alongside Stage 0. Stated willingness to pay is unreliable; who clicks is data. The warm audience is 131 leads, 93 scorecard completions, 12 clients and a dormant list, all this exact woman. Answers the demand question before Stage 1 is built rather than after.',
  },
  {
    id: 'rey-trade-mark',
    title: 'Clear, then file, the Rey name',
    description: 'A clearance search before any brand money is spent, then filing, the domain and the social handles.',
    status: 'in_progress',
    effort: 'M',
    notes: 'FIRST CHECK 14 Sep: REY itself looks registrable in Australia (no live REY mark in classes 9, 41, 42 or 44), but the name is not safe to build on. RAY (Ray Fitness Systems Inc, US, funded, rayfit.com, since 2024) is a voice-guided AI personal trainer that adapts to injuries: identical sound, near-identical product. KC REY Fitness (Kasey Tapara, NZ/AU) is a fat loss coaching app for women on Trainerize. Every obvious domain is taken (rey.com, rey.app, rey.ai, rey.health, rey.com.au, heyrey.com, getrey.com, reyapp.com); rey.fit, meetrey.com and heyrey.com.au were unregistered. Recommendation: choose a new name and run the same checks, then an attorney clearance before filing. Not covered by the Body Recode trade mark step. "Rey" is short and common, so a conflict is likely and must be found before the name is built into an app, a domain and marketing. Relevant classes are likely 9, 41, 42 and 44.',
  },
  {
    id: 'rey-brand-decision',
    title: 'How Rey relates to Body Recode',
    description: 'Whether Rey is its own brand, "Rey, powered by Body Recode", or sits under Body Recode, and the visual identity that follows.',
    status: 'planned',
    effort: 'S',
    notes: 'Brand decision, Kade\'s call. Affects the trade mark, the landing page, the app and whether an acquirer is buying Rey or Body Recode.',
  },
  {
    id: 'rey-landing-site',
    title: 'Rey\'s website',
    description: 'The pages she lands on, signs up from, and reads before paying.',
    status: 'planned',
    effort: 'M',
    blockedBy: 'rey-claims-language',
    notes: 'Every word must stay inside the wellness and coaching claims that keep Rey outside medical device regulation. See the claims step.',
  },

  /* ── Stage 1: product gaps found in the 14 Sep audit ─────────── */
  {
    id: 'rey-consumer-accounts',
    title: 'Consumer accounts and login',
    description: 'Real accounts rather than the coaching portal\'s private links: sign-in, password reset or passkeys, and a secure account for someone storing health information.',
    status: 'planned',
    effort: 'M',
    notes: 'The coaching portal works on per-client private links sent by a coach. A stranger signing up on the web needs a proper account that she controls, can recover, and can delete.',
  },
  {
    id: 'rey-first-week',
    title: 'The structured first seven days',
    description: 'Day zero read and first session, day two the read explained, day three the first readiness change, day five the trial reminder.',
    status: 'planned',
    effort: 'S',
    notes: 'Spec 11.3. The web half ships in Stage 1; the planned first refusal joins it in Stage 2.',
  },
  {
    id: 'rey-starting-from-zero',
    title: 'Starting from zero, for the woman who is not training',
    description: 'A first month of walking, sleep, food rhythm and short home sessions, ordered by her read, progressing into real training only as her readiness shows she can take it.',
    status: 'planned',
    effort: 'M',
    blockedBy: 'rey-pre-exercise-screening',
    notes: 'Added 14 Sep when Kade widened the audience: "I don\u2019t want to attract just women whose body has stopped responding." Every engine plan assumes a trained body. The scorecard already asks whether she is training (live 14 Sep) and records it on the lead. Spec 2 and 11.8.',
  },
  {
    id: 'rey-journey-edges',
    title: 'Missed weeks, illness, travel, and a read that does not fit',
    description: 'Lighter return after a week away, a re-check after a month, rest that counts when unwell, the same read with travel equipment, and a re-check when she says the read is not her.',
    status: 'planned',
    effort: 'M',
    notes: 'Spec 13.1, 13.2, 13.4, 13.5 and 13.7. Needed from the first paying customer, not only once voice exists.',
  },
  {
    id: 'rey-support',
    title: 'Support, and the route to a human',
    description: 'Rey answers "how do I" questions; billing, bad experiences and anything Rey should not answer reach a person within one business day.',
    status: 'planned',
    effort: 'S',
    notes: 'At launch the person is Kade. Needs an inbox, a written process and a way for Rey to hand over. Spec 7.3 and 15.7.',
  },
  {
    id: 'rey-accessibility',
    title: 'Accessibility',
    description: 'Adjustable text, captions for anything Rey says, nothing conveyed by colour alone, usable with a screen reader.',
    status: 'planned',
    effort: 'S',
    notes: 'Spec 15.9. The Disability Discrimination Act applies to online services.',
  },
  {
    id: 'rey-metrics',
    title: 'Consumer numbers from the first customer',
    description: 'Trial to paid, first-week activation, ninety-day retention, why people cancel, and what each subscriber cost to win.',
    status: 'planned',
    effort: 'M',
    notes: 'Distinct from the coach evidence steps. These are the numbers a raise is priced on, and churn reasons are only worth anything if asked at the moment of cancelling.',
  },

  /* ── Stage 1: clinical safety (14 Sep audit) ──────────────────── */
  {
    id: 'rey-clinical-advisor',
    title: 'An independent clinician reviews the doctrine before launch',
    description: 'A women\'s health GP or sports physician reviews what Rey will tell women, before any woman pays.',
    status: 'planned',
    effort: 'M',
    notes: 'For safety, credibility and liability. The peer review portal already exists and is ready to invite reviewers, so the mechanism is built; the reviewer is not chosen.',
  },
  {
    id: 'rey-pre-exercise-screening',
    title: 'Pre-exercise screening before any training',
    description: 'The standard adult pre-exercise screen, with anyone flagged needing clearance from a doctor before Rey programs anything.',
    status: 'planned',
    effort: 'M',
    notes: 'The coaching practice uses a health declaration and medical clearance with Kade checking. Rey has no Kade. The recognised tool is the Adult Pre-Exercise Screening System from Exercise and Sports Science Australia, Fitness Australia and Sports Medicine Australia. Probably the single most important liability control for a coachless training product.',
  },
  {
    id: 'rey-pregnancy-screen',
    title: 'Pregnancy, postpartum and breastfeeding at intake',
    description: 'Asked at the start, with Rey declining and explaining rather than programming.',
    status: 'planned',
    effort: 'S',
    notes: 'Spec 13.6 covers becoming pregnant while subscribed. This covers already being pregnant or postpartum at signup. The coaching intake gained a pregnant-now coach alert on 13 Sep; Rey needs the consumer version, which has no coach to alert.',
  },
  {
    id: 'rey-disordered-eating-screen',
    title: 'Screening for disordered eating before any nutrition targets',
    description: 'A short screen, with no calorie targets given to anyone at risk and a route to proper support.',
    status: 'planned',
    effort: 'M',
    notes: 'A nutrition product for women concerned about body composition carries real risk here, and a calorie target can cause harm. At-risk users receive no targets and are pointed to the Butterfly Foundation helpline, 1800 33 4673, and their GP.',
  },
  {
    id: 'rey-medication-handling',
    title: 'Medications that change the rules',
    description: 'Decide what Rey declines and what it adjusts for medications that alter appetite, heart rate, recovery or hormones.',
    status: 'planned',
    effort: 'S',
    notes: 'Appetite-suppressing weight medications, hormone therapy, thyroid medication, beta blockers and some antidepressants all change what safe training and nutrition look like. Medication capture already exists in the intake; the consumer rules do not. Internal only: medication names are never used in marketing.',
  },
  {
    id: 'rey-adverse-events',
    title: 'Recording and responding to harm',
    description: 'A log of anything Rey said that hurt someone, who reviews it, and when it changes the doctrine.',
    status: 'planned',
    effort: 'S',
    notes: 'Clinical governance. The doctrine\'s own rule is that evidence wins over doctrine; this is where that evidence is recorded. Includes how a complaint about harm is received and answered.',
  },

  /* ── Stage 1: legal, privacy and tax (14 Sep audit) ───────────── */
  {
    id: 'rey-tga-samd-position',
    title: 'Is Rey a regulated medical device',
    description: 'A regulatory opinion on whether Rey stays inside the wellness and coaching software exclusions, and what it may therefore say.',
    status: 'planned',
    effort: 'M',
    notes: 'The TGA regulates software that diagnoses or guides treatment of a condition as a medical device. General wellness software (exclusion 14B) and behavioural change or coaching software (exclusion 14C) are excluded, but only while they make no claims about a serious disease or condition, and every function in the product must qualify for the whole product to be excluded. The risk functions are interpreting perimenopause symptoms and interpreting bloodwork. Get the opinion before building them, because the answer shapes what they are allowed to say.',
  },
  {
    id: 'rey-claims-language',
    title: 'No diagnostic or treatment language, anywhere',
    description: 'Every read, screen, email, page and investor document describes interpretation and coaching, never diagnosis or treatment.',
    status: 'planned',
    effort: 'S',
    notes: 'The read\'s own schema already says the interpretation is probabilistic and non-diagnostic. Some of our own writing contradicted that: the How It Works explainer said "only the third is making a diagnosis", corrected 14 Sep. Language like that is exactly what could void the medical device exclusion for the whole product.',
  },
  {
    id: 'rey-terms-of-service',
    title: 'Terms of service, disclaimers and minimum age',
    description: 'Consumer terms reviewed by a lawyer: not medical advice, adults only, and nothing that would be an unfair term.',
    status: 'planned',
    effort: 'M',
    notes: 'Unfair contract terms in standard consumer contracts have attracted penalties since November 2023. Terms sit on top of consumer guarantees and can never remove them. Eighteen and over, so no one under age holds health data here.',
  },
  {
    id: 'rey-privacy-cross-border',
    title: 'Health information sent overseas',
    description: 'Disclosing, and protecting by contract, the health information sent to AI providers outside Australia.',
    status: 'planned',
    effort: 'M',
    notes: 'The database is hosted in Australia, but every read sends her health information to an AI provider in the United States, and voice will add at least one more provider. That is a cross-border disclosure under the Australian Privacy Principles. Needs disclosure, the providers\' data processing terms, and no-retention settings where they are offered. Related to the sub-processor register.',
  },
  {
    id: 'rey-automated-decisions-disclosure',
    title: 'Disclosing automated decisions',
    description: 'The privacy policy explains the decisions software makes about her using her information.',
    status: 'planned',
    effort: 'S',
    notes: 'Required from 10 December 2026 under the Privacy and Other Legislation Amendment Act 2024: a privacy policy must describe decisions made or substantially supported by a computer program that could significantly affect someone. Rey restricting her training, refusing her, or setting nutrition targets very likely qualifies. The regulator can issue infringement notices for a non-compliant policy.',
  },
  {
    id: 'rey-state-health-records',
    title: 'State health records laws',
    description: 'Confirm obligations under the Victorian, NSW and ACT health records Acts, which can apply alongside the federal Privacy Act.',
    status: 'planned',
    effort: 'S',
    notes: 'Also confirms the Privacy Act applies regardless of size: the small business exemption does not cover a business that provides a health service and holds health information.',
  },
  {
    id: 'rey-ai-disclosure',
    title: 'Rey says it is software',
    description: 'She always knows she is talking to software, never to a person, and the AI providers\' own rules for health use are met.',
    status: 'planned',
    effort: 'S',
    notes: 'Warm but direct must never become pretending to be human. The providers publish usage rules for consumer health applications that need checking before launch.',
  },
  {
    id: 'rey-spam-compliance',
    title: 'Consent and unsubscribe for every message',
    description: 'Every marketing email and text has consent and a working unsubscribe.',
    status: 'planned',
    effort: 'S',
    notes: 'Spam Act 2003. An unsubscribe system already exists for the coaching business; it needs extending to consumers. Service messages about her account are treated differently from marketing.',
  },
  {
    id: 'rey-insurance',
    title: 'Insurance',
    description: 'Professional indemnity, public and product liability, and cyber insurance, held by the company.',
    status: 'planned',
    effort: 'M',
    blockedBy: 'incorporate',
    notes: 'Separate from the coachless liability position, which decides what cover is needed. Cyber insurance matters specifically because the business holds health information.',
  },
  {
    id: 'rey-gst-tax',
    title: 'GST and tax on subscriptions',
    description: 'Prices shown to consumers including GST, registration handled, and tax on sales to people overseas.',
    status: 'planned',
    effort: 'S',
    notes: 'Accountant\'s work. GST registration is required from $75,000 turnover and consumer prices must be shown GST-inclusive, so whether $199 includes GST must be decided before it is published. Selling on the web to people outside Australia can trigger other countries\' digital services taxes. This needs to be exactly right from the first sale.',
  },

  /* ── Stage 2 additions (14 Sep audit) ─────────────────────────── */
  {
    id: 'rey-app-store-compliance',
    title: 'App store rules',
    description: 'Health app review, the rules on health data from phones, how the app may refer to web signup, and in-app account deletion.',
    status: 'planned',
    effort: 'M',
    notes: 'Apple requires that an app offering account creation lets the user delete the account from inside the app. Health data read from the phone cannot be used for advertising. The web-first plan is allowed, but how the app may point to buying elsewhere is tightly restricted and must be designed to the rules.',
  },
  {
    id: 'rey-voice-data-policy',
    title: 'What happens to her voice',
    description: 'Whether recordings are kept, what transcripts are stored, for how long, and what the voice providers retain.',
    status: 'planned',
    effort: 'S',
    notes: 'Voice is personal information and she will say health information aloud. Default should be no recordings retained. Stated plainly in the privacy policy.',
  },
  {
    id: 'rey-exercise-content',
    title: 'Exercise demonstrations and the rights to them',
    description: 'The video, images and cues she sees for each movement, owned or properly licensed.',
    status: 'planned',
    effort: 'M',
    notes: 'The video pipeline already exists and could produce owned content. Stock or third-party demonstration libraries need licences that allow commercial app use.',
  },

  /* ── Later ───────────────────────────────────────────────── */
  {
    id: 'rey-full-meal-plans',
    title: 'Full meal plans, behind the evidence gate',
    description: 'Twenty-one meals with swaps and per-meal detail.',
    status: 'deferred',
    effort: 'L',
    notes: 'Ships when the nutrition engine runs clean for real people without correction: a run of consecutive plans that would have been signed off unchanged. A condition, not a date. Under-eating is the most common harm in exactly this audience. Spec 7.4.',
  },
  {
    id: 'rey-audience-b',
    title: 'Widen to busy professionals of both sexes',
    description: 'The second audience, once the first is working.',
    status: 'deferred',
    effort: 'M',
    notes: 'A for the marketing, both in the build, B when A works. Realistically around a thousand subscribers. Spec 2.',
  },
  {
    id: 'rey-gym-portability',
    title: 'Her read follows her into any gym',
    description: 'The intelligence belongs to her profile, not to the facility.',
    status: 'deferred',
    effort: 'L',
    notes: 'The strongest idea in the 2024 origin work, and the consumer mirror of the platform strategy. Not version one. Spec 9.',
  },
]
