'use client'

import { useState, useTransition } from 'react'
import { useRouter } from 'next/navigation'
import GenerationProgressOverlay from '@/components/generation-progress-overlay'

interface ExistingFeedback {
  id: string
  interpretation: string
  reframe: string | null
  next_focus: string
  email_sent_at: string | null
  updated_at: string
  auto_generated_at?: string | null
  auto_send_scheduled_at?: string | null
}

/**
 * Two modes:
 *   - "view"  — feedback exists, render it as a Past response card (same shape
 *               the client sees) with an Edit button to revise.
 *   - "edit"  — show the editable form (3 textareas + Generate + Save buttons).
 *
 * Default to "view" when feedback already exists on page load, "edit" when not.
 * After a successful save, switch back to "view" so the page reflects the
 * stored state instead of staying in active-editing mode.
 */
export default function CheckinFeedbackForm({
  checkinId,
  existing: existingFromServer,
  clientFirstName,
  skippedAt: skippedAtFromServer,
  skipReason: skipReasonFromServer,
  autoGeneratedAt,
  autoSendScheduledAt,
  autoResponseFailedReason,
  autoResponseAttemptedAt,
  coachDraftNotes,
}: {
  checkinId: string
  existing: ExistingFeedback | null
  clientFirstName: string
  skippedAt: string | null
  skipReason: string | null
  autoGeneratedAt: string | null
  autoSendScheduledAt: string | null
  autoResponseFailedReason: string | null
  autoResponseAttemptedAt: string | null
  /** Steer the coach typed last time they generated. Persisted on the check-in. */
  coachDraftNotes: string | null
}) {
  const router = useRouter()
  // Local copy of the saved feedback so we can flip back to view mode without
  // a router round-trip on save. Server stays the source of truth on reload.
  const [existing, setExisting] = useState<ExistingFeedback | null>(existingFromServer)
  const [skippedAt, setSkippedAt] = useState<string | null>(skippedAtFromServer)
  const [skipReason, setSkipReason] = useState<string | null>(skipReasonFromServer)
  const [mode, setMode] = useState<'view' | 'edit'>(existingFromServer ? 'view' : 'edit')

  const [interpretation, setInterpretation] = useState(existingFromServer?.interpretation ?? '')
  const [reframe, setReframe] = useState(existingFromServer?.reframe ?? '')
  const [nextFocus, setNextFocus] = useState(existingFromServer?.next_focus ?? '')
  const [coachNotes, setCoachNotes] = useState(coachDraftNotes ?? '')
  const [pending, startTransition] = useTransition()
  const [generating, setGenerating] = useState(false)
  const [skipping, setSkipping] = useState(false)
  const [status, setStatus] = useState<string | null>(null)
  const [error, setError] = useState<string | null>(null)

  // Auto-draft state: this feedback row was created by the auto-response
  // pipeline. 2026-06-15: the 4h auto-send was removed. Now Kade approves
  // the send via the [Approve] preview email (or via the Send now button
  // below). Nothing reaches the client without an explicit click.
  const isAutoDraftPending =
    !!existing &&
    !existing.email_sent_at &&
    !!autoGeneratedAt
  void autoSendScheduledAt // historical column, no longer driver

  async function skip() {
    setError(null); setStatus(null)
    const reason = prompt(`Mark this check-in as skipped (no coach response needed)? Optional note for your own records:`)
    if (reason === null) return // cancelled
    setSkipping(true)
    try {
      const res = await fetch(`/api/weekly-checkins/${checkinId}/skip`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ action: 'skip', reason: reason.trim() || null }),
      })
      const json = await res.json()
      if (!res.ok) { setError(json.error ?? 'Skip failed'); return }
      setSkippedAt(json.checkin?.coach_skipped_at ?? new Date().toISOString())
      setSkipReason(json.checkin?.coach_skip_reason ?? null)
      setStatus('Check-in marked as skipped. It will not appear as a pending action.')
      router.refresh()
    } catch (err) {
      setError((err as Error).message)
    } finally {
      setSkipping(false)
    }
  }

  async function unskip() {
    setError(null); setStatus(null); setSkipping(true)
    try {
      const res = await fetch(`/api/weekly-checkins/${checkinId}/skip`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ action: 'unskip' }),
      })
      const json = await res.json()
      if (!res.ok) { setError(json.error ?? 'Unskip failed'); return }
      setSkippedAt(null)
      setSkipReason(null)
      setStatus('Skip cleared. This check-in will appear as pending again if it has no response.')
      router.refresh()
    } catch (err) {
      setError((err as Error).message)
    } finally {
      setSkipping(false)
    }
  }

  async function generateDraft() {
    setError(null)
    setStatus(null)
    const hasContent = interpretation.trim() || reframe.trim() || nextFocus.trim()
    if (hasContent) {
      const ok = confirm('This will overwrite your current draft with an AI-generated one. Continue?')
      if (!ok) return
    }
    setGenerating(true)
    try {
      const res = await fetch(`/api/weekly-checkins/${checkinId}/feedback/generate`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ coach_notes: coachNotes.trim() || null }),
      })
      const json = await res.json()
      if (!res.ok) {
        setError(json.error ?? 'Generation failed')
        return
      }
      const draft = json.draft ?? {}
      setInterpretation(draft.interpretation ?? '')
      setReframe(draft.reframe ?? '')
      setNextFocus(draft.next_focus ?? '')
      setStatus(
        coachNotes.trim()
          ? 'Draft generated using your notes. Review, edit if needed, then click Save and email to approve.'
          : 'Draft generated. Review, edit if needed, then click Save and email to approve.'
      )
    } catch (err) {
      setError((err as Error).message ?? 'Generation failed')
    } finally {
      setGenerating(false)
    }
  }

  async function submit(sendEmail: boolean) {
    setError(null)
    setStatus(null)
    if (!interpretation.trim()) { setError('Interpretation is required.'); return }
    if (!nextFocus.trim()) { setError('Next focus is required.'); return }

    startTransition(async () => {
      const res = await fetch(`/api/weekly-checkins/${checkinId}/feedback`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          interpretation: interpretation.trim(),
          reframe: reframe.trim() || null,
          next_focus: nextFocus.trim(),
          send_email: sendEmail,
        }),
      })
      const json = await res.json()
      if (!res.ok) {
        setError(json.error ?? 'Failed to save')
        return
      }
      // Update local copy with what we just saved so the view-mode card
      // shows the latest values immediately, no refresh flicker.
      const savedAt = new Date().toISOString()
      const newExisting: ExistingFeedback = {
        id: json.feedback?.id ?? existing?.id ?? 'unknown',
        interpretation: interpretation.trim(),
        reframe: reframe.trim() || null,
        next_focus: nextFocus.trim(),
        email_sent_at: sendEmail ? (json.feedback?.email_sent_at ?? savedAt) : existing?.email_sent_at ?? null,
        updated_at: savedAt,
      }
      setExisting(newExisting)
      setStatus(
        sendEmail
          ? `Saved and emailed to ${clientFirstName}.`
          : 'Saved as draft. Client will not receive this until you send it.'
      )
      setMode('view')
      router.refresh()
    })
  }

  // ── SKIPPED + NO FEEDBACK ─────────────────────────────────────────────
  // If the coach has skipped this check-in and there's no feedback row,
  // render a small "Skipped" card with an Unskip control. If they want to
  // write feedback retroactively, they unskip first then the form appears.
  if (skippedAt && !existing) {
    return (
      <div className="bg-[#F4F6F9] border border-[#E8EAEE] rounded-xl overflow-hidden">
        <div className="px-5 py-3 border-b border-[#E8EAEE] flex items-center justify-between gap-3 flex-wrap">
          <div className="flex items-center gap-3 flex-wrap">
            <p className="text-[12px] font-medium text-[#666D7A]">Coach response</p>
            <span className="text-[11.5px] font-medium px-2 py-0.5 rounded bg-[#EFF1F4] border border-[#CFD4DC] text-[#666D7A]">
              Skipped {new Date(skippedAt).toLocaleDateString('en-AU', { day: 'numeric', month: 'short' })}
            </span>
          </div>
          <button
            type="button"
            onClick={unskip}
            disabled={skipping}
            className="text-[12.5px] font-medium text-blue-700 hover:text-blue-200 transition-colors disabled:opacity-50"
          >
            {skipping ? 'Working…' : 'Unskip and write response →'}
          </button>
        </div>
        <div className="px-5 py-5">
          <p className="text-sm text-[#141821] leading-relaxed">
            You marked this check-in as not needing a coach response.
            {clientFirstName} sees no Coach response card on their portal for this check-in.
          </p>
          {skipReason && (
            <div className="mt-3 rounded-lg bg-[#FFFFFF] border border-[#E8EAEE] p-3">
              <p className="text-[11.5px] font-medium text-[#666D7A] mb-1">Your note</p>
              <p className="text-[12.5px] text-[#141821] whitespace-pre-wrap leading-relaxed">{skipReason}</p>
            </div>
          )}
        </div>
        {error && <p className="px-5 pb-4 text-[12.5px] text-red-700">{error}</p>}
        {status && <p className="px-5 pb-4 text-[12.5px] text-blue-500">{status}</p>}
      </div>
    )
  }

  // ── AUTO-DRAFT PENDING BANNER ─────────────────────────────────────────
  // Renders above the response card when an AI draft is awaiting Kade's
  // approval. 2026-06-15: no countdown, no auto-send. The banner exists
  // to remind Kade that the inbox preview email is the primary channel
  // and these dashboard buttons (Send now, Skip) are the same actions
  // expressed here.
  function AutoDraftBanner() {
    if (!isAutoDraftPending) return null
    return (
      <div className="mb-3 rounded-lg border border-[#1B6DFC]/30 bg-[#1B6DFC]/5 px-4 py-3 flex items-center justify-between gap-3 flex-wrap">
        <div className="min-w-0">
          <p className="text-[12px] font-medium text-[#1B6DFC]">AI draft, awaiting your approval</p>
          <p className="text-[12.5px] text-[#43474F] mt-1 leading-relaxed">
            This response was AI-generated when {clientFirstName} submitted the check-in. Nothing has been sent to {clientFirstName}. The Approve &amp; Send button in your inbox does the same thing as Send now below.
          </p>
        </div>
        <div className="flex items-center gap-2 shrink-0">
          <button
            type="button"
            onClick={() => submit(true)}
            disabled={pending}
            className="text-[12.5px] font-medium px-3 py-1.5 bg-[#1B6DFC] text-white rounded-lg hover:bg-[#1057CC] transition-colors disabled:opacity-50"
          >
            Send now
          </button>
          <button
            type="button"
            onClick={skip}
            disabled={skipping}
            className="text-[12.5px] font-medium px-3 py-1.5 border border-[#E8EAEE] text-[#666D7A] rounded-lg hover:border-[#1B6DFC] hover:text-[#1B6DFC] transition-colors disabled:opacity-50"
          >
            Skip instead
          </button>
        </div>
      </div>
    )
  }

  // ── AI FAILURE BANNER ─────────────────────────────────────────────────
  // Renders when the auto-response pipeline ran but failed to produce a
  // clean draft (jargon leak after 3 retries, parse error, etc.). No
  // feedback row exists yet; coach writes the response manually.
  function AiFailureBanner() {
    if (existing) return null // a feedback row exists, no failure
    if (!autoResponseAttemptedAt || !autoResponseFailedReason) return null
    return (
      <div className="mb-3 rounded-lg border border-amber-300 bg-amber-50 px-4 py-3">
        <p className="text-[12px] font-medium text-amber-700">AI auto-response failed</p>
        <p className="text-[12.5px] text-[#43474F] mt-1 leading-relaxed">
          The auto-response pipeline ran at {new Date(autoResponseAttemptedAt).toLocaleString('en-AU', { timeZone: 'Australia/Brisbane', weekday: 'short', day: 'numeric', month: 'short', hour: 'numeric', minute: '2-digit', hour12: true })} but could not produce a clean draft. Reason: <span className="font-mono text-[10px]">{autoResponseFailedReason}</span>. Please write the response manually below, or click Generate response to try again.
        </p>
      </div>
    )
  }

  // ── VIEW MODE ───────────────────────────────────────────────────────────
  if (mode === 'view' && existing) {
    const sent = !!existing.email_sent_at
    return (
      <div>
      <AutoDraftBanner />
      <div className="bg-[#F4F6F9] border border-[#E8EAEE] rounded-xl overflow-hidden">
        <div className="px-5 py-3 border-b border-[#E8EAEE] flex items-center justify-between gap-3 flex-wrap">
          <div className="flex items-center gap-3 flex-wrap">
            <p className="text-[12px] font-medium text-blue-500">Coach response</p>
            <span
              className={`text-[11.5px] font-medium px-2 py-0.5 rounded ${
                sent
                  ? 'bg-blue-50 border border-blue-200 text-blue-700'
                  : 'bg-amber-50 border border-amber-200 text-amber-700'
              }`}
            >
              {sent ? `Emailed ${formatShort(existing.email_sent_at!)}` : 'Draft (not sent)'}
            </span>
            <span className="text-[10px] text-[#666D7A]">
              Last saved {formatShort(existing.updated_at)}
            </span>
          </div>
          <button
            type="button"
            onClick={() => { setMode('edit'); setStatus(null); setError(null) }}
            className="text-[12.5px] font-medium text-blue-700 hover:text-blue-200 transition-colors"
          >
            Edit response →
          </button>
        </div>
        <div className="px-5 py-5 space-y-5">
          <SavedSection title="Interpretation" body={existing.interpretation} />
          {existing.reframe && <SavedSection title="Reframe" body={existing.reframe} />}
          <SavedSection title="This week, hold this" body={existing.next_focus} accent />
        </div>
        {status && <p className="px-5 pb-4 text-[12.5px] text-blue-500">{status}</p>}
      </div>
      </div>
    )
  }

  // ── EDIT MODE ───────────────────────────────────────────────────────────
  const previouslyEmailed = !!existing?.email_sent_at

  return (
    <div>
    <GenerationProgressOverlay
      active={generating}
      title="Drafting Coach Response"
      stages={[
        { start: 0,  label: 'Reading this check-in plus the last 4 check-ins for trajectory' },
        { start: 4,  label: 'Reading CFFS, active program, active nutrition plan' },
        { start: 10, label: 'Drafting the 3 fields (Interpretation, Reframe, Next focus)' },
        { start: 22, label: 'Scanning for banned client-facing terms' },
        { start: 27, label: 'Auto-retrying if any banned terms leaked' },
        { start: 40, label: 'Returning the draft for your review' },
        { start: 60, label: 'Taking longer than usual, give it another moment' },
      ]}
      disclaimer="Coach Response drafting uses Claude Haiku 4.5 with automatic banned-term retry. Typical: 20 to 40 seconds. The page is not frozen, please don't refresh."
    />
    <AutoDraftBanner />
    <AiFailureBanner />
    <div className="bg-[#F4F6F9] border border-[#E8EAEE] rounded-xl p-5">
      <div className="flex items-center justify-between mb-4 gap-3 flex-wrap">
        <p className="text-[12px] font-medium text-blue-500">
          {existing ? 'Edit coach response' : 'Coach response'}
        </p>
        <div className="flex items-center gap-3">
          {previouslyEmailed && (
            <p className="text-[10px] text-[#666D7A]">
              Emailed {formatShort(existing!.email_sent_at!)}
            </p>
          )}
          {existing && (
            <button
              type="button"
              onClick={() => { setMode('view'); setStatus(null); setError(null) }}
              className="text-[12.5px] text-[#666D7A] hover:text-[#141821] transition-colors"
            >
              Cancel
            </button>
          )}
        </div>
      </div>

      <p className="text-[12.5px] text-[#666D7A] leading-relaxed mb-4">
        Three fields go to {clientFirstName} as a dark-template email and appear under this check-in in their portal. Reframe is optional, use it when {clientFirstName} is misreading their own signal.
      </p>

      <div className="mb-5 rounded-lg border border-[#E8EAEE] bg-[#FFFFFF] px-4 py-3">
        <div className="flex items-start justify-between gap-3">
          <div className="min-w-0">
            <p className="text-[12px] font-medium text-blue-500">Draft with AI</p>
            <p className="text-[12.5px] text-[#666D7A] mt-1 leading-relaxed">
              Pulls this check-in (including the training and nutrition answers), the synthesis, the last 4 check-ins, the active program and nutrition plan, and the last 3 responses {clientFirstName} was sent. You review and approve before anything sends.
            </p>
          </div>
          <button
            type="button"
            onClick={generateDraft}
            disabled={generating || pending}
            className="shrink-0 px-3 py-2 bg-blue-50 border border-blue-300 hover:bg-blue-100 text-blue-700 text-[12.5px] font-medium rounded-lg transition-colors disabled:opacity-50"
          >
            {generating ? 'Generating…' : 'Generate response'}
          </button>
        </div>

        <div className="mt-3 pt-3 border-t border-[#E8EAEE]">
          <label className="block text-[12px] font-medium text-[#666D7A] mb-1">
            Add details for the AI (optional)
          </label>
          <p className="text-[12.5px] text-[#666D7A] mb-2 leading-relaxed">
            Anything you know that the check-in does not show, or what you want this response to land on. Whatever you name here gets addressed, and if you name a focus it becomes the &ldquo;this week, hold this&rdquo; anchor. Saved with the check-in, so it is still here next time you generate.
          </p>
          <textarea
            value={coachNotes}
            onChange={e => setCoachNotes(e.target.value)}
            rows={3}
            placeholder={`e.g. He's added 3 runs a week for a half marathon in October. Don't make this about food again, the anchor should be protecting his three gym sessions around the running load. Mention he's said "feeling stronger" two weeks running.`}
            className="w-full bg-[#FBFCFD] border border-[#E8EAEE] rounded-lg p-3 text-sm text-[#141821] placeholder:text-[#98A0AD] focus:outline-none focus:border-blue-500/60 resize-y"
          />
        </div>
      </div>

      <div className="space-y-5">
        <Field
          label="Interpretation"
          hint="What you are seeing in this check-in. The read, not the directive."
          value={interpretation}
          onChange={setInterpretation}
          required
          rows={6}
          placeholder="e.g. Recovery has stepped down two notches in a week and capacity is starting to compress. Sleep and appetite are holding, so the foundations are intact, but the load source looks upstream of training..."
        />
        <Field
          label="Reframe (optional)"
          hint="Use when the client is misreading their own pattern. Leave blank if not needed."
          value={reframe}
          onChange={setReframe}
          rows={4}
          placeholder="e.g. The clothes feeling tighter is much more likely abdominal bloating than weight gain..."
        />
        <Field
          label="This week, hold this"
          hint="One thing for the client to anchor on this week."
          value={nextFocus}
          onChange={setNextFocus}
          required
          rows={3}
          placeholder="e.g. Keep training as your stress release, not as an extra demand. If a session feels like adding load, swap it for a 20-minute walk and a sleep-priority night."
        />
      </div>

      {error && (
        <p className="mt-4 text-[12.5px] text-red-700">{error}</p>
      )}
      {status && (
        <p className="mt-4 text-[12.5px] text-blue-500">{status}</p>
      )}

      <div className="mt-6 flex flex-wrap items-center gap-3">
        <button
          type="button"
          disabled={pending}
          onClick={() => submit(true)}
          className="px-4 py-2.5 bg-blue-500 hover:bg-blue-500 text-white text-[12.5px] font-medium rounded-lg transition-colors disabled:opacity-50"
        >
          {pending ? 'Working…' : previouslyEmailed ? 'Save and re-send email' : 'Save and email client'}
        </button>
        <button
          type="button"
          disabled={pending}
          onClick={() => submit(false)}
          className="px-4 py-2.5 border border-[#E8EAEE] hover:border-[#CFD4DC] text-[#141821] text-[12.5px] font-medium rounded-lg transition-colors disabled:opacity-50"
        >
          Save without sending
        </button>
        {!existing && !skippedAt && (
          <button
            type="button"
            disabled={skipping}
            onClick={skip}
            className="ml-auto text-[12.5px] font-medium text-[#666D7A] hover:text-[#141821] transition-colors disabled:opacity-50"
          >
            {skipping ? 'Working…' : 'Skip without responding'}
          </button>
        )}
      </div>
    </div>
    </div>
  )
}

function Field({
  label,
  hint,
  value,
  onChange,
  rows,
  required,
  placeholder,
}: {
  label: string
  hint: string
  value: string
  onChange: (v: string) => void
  rows: number
  required?: boolean
  placeholder?: string
}) {
  return (
    <div>
      <label className="block text-[12px] font-medium text-[#666D7A] mb-1">{label}</label>
      <p className="text-[12.5px] text-[#666D7A] mb-2 leading-relaxed">{hint}</p>
      <textarea
        value={value}
        onChange={e => onChange(e.target.value)}
        rows={rows}
        placeholder={placeholder}
        className="w-full bg-[#FFFFFF] border border-[#E8EAEE] rounded-lg p-3 text-sm text-[#141821] placeholder:text-[#141821] focus:outline-none focus:border-blue-500/60 resize-y"
      />
    </div>
  )
}

function SavedSection({ title, body, accent }: { title: string; body: string; accent?: boolean }) {
  return (
    <div>
      <p className={`text-[12px] font-medium mb-2 ${accent ? 'text-blue-500' : 'text-[#666D7A]'}`}>{title}</p>
      <div className="text-sm text-[#141821] leading-relaxed space-y-3 whitespace-pre-wrap">{body}</div>
    </div>
  )
}

function formatShort(isoDate: string): string {
  return new Date(isoDate).toLocaleDateString('en-AU', { day: 'numeric', month: 'short' })
}
