import { createAdminClient } from '@/lib/supabase/admin'
import { notFound } from 'next/navigation'
import Link from 'next/link'
import { getCheckinSections } from '@/lib/weekly-checkin-questions'
import CheckinFeedbackForm from './feedback-form'

export default async function CheckInDetailPage({
  params,
}: {
  params: Promise<{ id: string; week: string; form: string }>
}) {
  const { id, week, form } = await params
  const formType = form.toUpperCase() as 'A' | 'B'
  const weekNumber = parseInt(week)

  if (!['A', 'B'].includes(formType) || isNaN(weekNumber)) notFound()

  const admin = createAdminClient()

  const { data: client } = await admin
    .from('clients')
    .select('id, name')
    .eq('id', id)
    .maybeSingle()

  if (!client) notFound()

  const { data: checkin } = await admin
    .from('weekly_checkins')
    .select('id, responses, submitted_at, coach_skipped_at, coach_skip_reason, auto_response_attempted_at, auto_response_failure_reason, coach_draft_notes')
    .eq('client_id', id)
    .eq('week_number', weekNumber)
    .eq('form_type', formType)
    .maybeSingle()

  if (!checkin) notFound()

  const { data: feedback } = await admin
    .from('weekly_checkin_feedback')
    .select('id, interpretation, reframe, next_focus, email_sent_at, updated_at, auto_generated_at, auto_send_scheduled_at')
    .eq('weekly_checkin_id', checkin.id)
    .maybeSingle()

  // Include the Training + Nutrition review sections. This page used to render
  // the reflective sections only, so the coach never saw the training or
  // nutrition adherence answers the client submitted (2026-08-17).
  const sections = getCheckinSections(formType, { includeNutrition: true })
  const responses = checkin.responses as Record<string, string>

  const submittedAt = new Date(checkin.submitted_at).toLocaleString('en-AU', {
    timeZone: 'Australia/Brisbane',
    weekday: 'long',
    day: 'numeric',
    month: 'long',
    year: 'numeric',
    hour: 'numeric',
    minute: '2-digit',
    hour12: true,
  })

  return (
    <div className="min-h-screen bg-[#FFFFFF] p-6 md:p-10">
      <div className="max-w-2xl mx-auto">

        <div className="mb-8">
          <Link
            href={`/dashboard/clients/${id}`}
            className="text-xs text-stone-500 hover:text-stone-700 transition-colors"
          >
            ← Back to {client.name}
          </Link>
        </div>

        <div className="mb-8">
          <p className="text-xs font-bold tracking-widest text-blue-500 uppercase mb-1">
            Week {weekNumber} · Form {formType}
          </p>
          <h1 className="text-2xl font-bold text-[#1A1A1A] tracking-tight">{client.name}</h1>
          <p className="text-stone-500 text-sm mt-1">Submitted {submittedAt}</p>
        </div>

        <div className="space-y-6">
          <CheckinFeedbackForm
            checkinId={checkin.id}
            existing={feedback ?? null}
            clientFirstName={client.name?.split(' ')[0] ?? 'your client'}
            skippedAt={checkin.coach_skipped_at ?? null}
            skipReason={checkin.coach_skip_reason ?? null}
            autoGeneratedAt={feedback?.auto_generated_at ?? null}
            autoSendScheduledAt={feedback?.auto_send_scheduled_at ?? null}
            autoResponseFailedReason={checkin.auto_response_failure_reason ?? null}
            autoResponseAttemptedAt={checkin.auto_response_attempted_at ?? null}
            coachDraftNotes={checkin.coach_draft_notes ?? null}
          />

          {sections.map(section => {
            const answered = section.questions.filter(q => responses[q.id])
            if (answered.length === 0) return null
            return (
              <div key={section.title} className="bg-stone-100 border border-stone-200 rounded-xl p-5">
                <p className="text-xs font-bold uppercase tracking-widest text-stone-500 mb-4">{section.title}</p>
                <div className="space-y-5">
                  {answered.map(q => (
                    <div key={q.id}>
                      <p className="text-xs text-stone-500 mb-1.5 leading-relaxed">{q.text}</p>
                      <p className="text-sm text-stone-800 leading-relaxed">{responses[q.id]}</p>
                    </div>
                  ))}
                </div>
              </div>
            )
          })}
        </div>

      </div>
    </div>
  )
}
