'use client'

import { useState } from 'react'
import { brand } from '@/config/tenant'

/**
 * The collection notice, shown where health information is actually collected
 * rather than as a link in the footer.
 *
 * WHY (regulatory research G1b, 17 Sep 2026): almost everything we collect is
 * health information, which Australian privacy law treats as sensitive.
 * Australian Privacy Principle 5 says the notice has to be given at or before
 * collection and has to cover specific things, including whether information
 * goes overseas and to which countries. Australian Privacy Principle 3.3 says
 * sensitive information generally needs consent, and the regulator's guidance
 * says consent should be informed, voluntary, current, specific, and not
 * bundled into a general agreement.
 *
 * So: the eight points below are the Principle 5.2 list in plain words, and
 * HealthConsent is a separate, unticked box, not a line inside terms.
 *
 * This is written to be read. If it ever needs a lawyer's wording instead,
 * change it here once and every collection point follows.
 */

const POINTS: { heading: string; body: string }[] = [
  {
    heading: 'What we are collecting',
    body: 'Health information: how you sleep, how stress lands, your energy, your cycle and hormonal status, medications, injuries and conditions, and where your body holds what it holds. Measurements, photographs and blood results only if you choose to give them.',
  },
  {
    heading: 'Why',
    body: 'To write your read and to build your training, nutrition and daily routine. Nothing here is collected to sell you something later.',
  },
  {
    heading: 'What happens if you leave something out',
    body: 'You can skip any question. The read is built from what you give us, so gaps make it less specific, not wrong.',
  },
  {
    heading: 'Who else sees it',
    body: 'Your coach. Our database and file storage, held in Sydney. The artificial intelligence model that writes your read, which processes it in the United States on our instructions only and does not use it to train itself. Our email and text providers see your contact details, not your answers.',
  },
  {
    heading: 'A computer writes the first draft',
    body: 'Your read, program and plan are generated by an artificial intelligence model. A coach reviews it before it reaches you, and can change or hold it. The rules that stop a plan and send you to your doctor are fixed rules, not the model deciding.',
  },
  {
    heading: 'How long we keep it',
    body: 'While we are working together, then seven years, which is what health record law requires of health service providers in some states. You can ask us to delete your photographs and blood results at any time.',
  },
  {
    heading: 'Changing your mind',
    body: 'You can withdraw your consent, ask to see what we hold, ask us to correct it, or ask us to delete it. Email us and we will answer within 30 days.',
  },
  {
    heading: 'If we get it wrong',
    body: 'Tell us first. If you are not satisfied, you can complain to the Office of the Australian Information Commissioner at oaic.gov.au or on 1300 363 992.',
  },
]

export function CollectionNotice({ compact = false }: { compact?: boolean }) {
  const [open, setOpen] = useState(false)

  return (
    <div className="rounded-2xl border border-[#E8EAEE] bg-[#F7F8FA] px-4 py-3.5">
      <p className="text-[13px] leading-relaxed text-[#43474F]">
        <strong className="text-[#141821]">What you tell us here is health information.</strong>{' '}
        We hold it under Australian privacy law, we use it to write your read and build your plan, and we
        never sell it.
      </p>
      <button
        type="button"
        onClick={() => setOpen(o => !o)}
        className="mt-2 text-[12.5px] font-semibold text-[#1056D6] hover:underline"
      >
        {open ? 'Hide the detail' : 'What we collect, who sees it, how long we keep it'}
      </button>

      {open && (
        <div className="mt-3 space-y-3 border-t border-[#E8EAEE] pt-3">
          {POINTS.map(pt => (
            <div key={pt.heading}>
              <p className="text-[12px] font-bold text-[#141821]">{pt.heading}</p>
              <p className="text-[12.5px] leading-relaxed text-[#5A6069]">{pt.body}</p>
            </div>
          ))}
          <p className="text-[12px] text-[#6B7280]">
            The full policy is at{' '}
            <a href="/privacy" target="_blank" rel="noreferrer" className="text-[#1056D6] hover:underline">
              bodyrecode.au/privacy
            </a>
            . Questions to{' '}
            <a href={`mailto:${brand().supportEmail}`} className="text-[#1056D6] hover:underline">
              {brand().supportEmail}
            </a>
            .
          </p>
        </div>
      )}

      {!compact && !open && (
        <p className="mt-2 text-[12px] text-[#6B7280]">
          Full policy:{' '}
          <a href="/privacy" target="_blank" rel="noreferrer" className="text-[#1056D6] hover:underline">
            bodyrecode.au/privacy
          </a>
        </p>
      )}
    </div>
  )
}

/**
 * The tick itself. Separate from any terms agreement on purpose: bundled
 * consent is not consent for sensitive information.
 */
export function HealthConsent({
  checked,
  onChange,
  label,
}: {
  checked: boolean
  onChange: (v: boolean) => void
  /** Override for contexts where "these questions" is the wrong noun. */
  label?: string
}) {
  return (
    <label className="flex items-start gap-3 rounded-2xl border border-[#E8EAEE] bg-white px-4 py-3.5 cursor-pointer">
      <input
        type="checkbox"
        checked={checked}
        onChange={e => onChange(e.target.checked)}
        className="mt-[3px] h-4 w-4 shrink-0 accent-[#1B6DFC]"
      />
      <span className="text-[13px] leading-relaxed text-[#43474F]">
        {label ??
          'I agree to Body Recode collecting the health information in these questions, and to it being processed by the providers described above, to write my read and build my plan.'}
      </span>
    </label>
  )
}
