/**
 * Weekly Pattern Report layout.
 *
 * Intentionally slim - this is a 1-page Friday-afternoon read. Three short
 * sections (This week / Trend / One focus). Same editorial DNA as the other
 * deep-dive layouts but shorter and prescriptive.
 */

const SIGNAL_BLUE = '#1B6DFC'
const INK = '#1A1A1A'
const BODY = '#2B2B2B'
const MUTED = '#6B6B6B'
const SUBTLE = '#999999'
const HAIRLINE = '#E5E5E5'
const PAPER = '#FFFFFF'
const SANS_FONT = "ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Inter', 'Segoe UI', sans-serif"

export interface WeeklyPatternLayoutData {
  sections: {
    wpr_this_week: string
    wpr_trend: string
    wpr_one_focus: string
  }
  memberName: string
  patternLabel: string
  blockLabel: string
  weekNumber: number
  deliveryNumber: number
  generated_at: string
}

const SECTIONS: Array<{ key: keyof WeeklyPatternLayoutData['sections']; label: string }> = [
  { key: 'wpr_this_week',  label: 'This week, what your signal is doing' },
  { key: 'wpr_trend',      label: 'The trend across the last four weeks' },
  { key: 'wpr_one_focus',  label: 'The one thing to hold this week' },
]

export default function WeeklyPatternLayout({ data }: { data: WeeklyPatternLayoutData }) {
  const dateLabel = new Date(data.generated_at).toLocaleDateString('en-AU', {
    day: 'numeric', month: 'long', year: 'numeric',
  })
  const meta = [
    `For ${data.memberName}`,
    `${data.patternLabel} · Block ${data.blockLabel}, Week ${data.weekNumber}`,
    `Delivery ${data.deliveryNumber} of 4`,
    dateLabel,
  ].filter(Boolean).join(' · ')

  return (
    <html lang="en" style={{ background: PAPER }}>
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preload" href="/logo-black.png" as="image" />
        <style>{`
          @page { size: A4; margin: 22mm 18mm 22mm 18mm; }
          html, body { margin: 0; padding: 0; background: ${PAPER}; color: ${INK}; font-family: ${SANS_FONT}; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
          .doc { max-width: 640px; margin: 0 auto; padding: 32px 0 48px; }
          .logo { width: 80px; height: auto; }
          .eyebrow { font-size: 11px; font-weight: 700; color: ${SIGNAL_BLUE}; letter-spacing: 0.14em; text-transform: uppercase; margin: 28px 0 14px; }
          h1 { font-size: 36px; line-height: 1.1; letter-spacing: -0.025em; margin: 0 0 14px; font-weight: 800; color: ${INK}; }
          .sub { font-size: 15px; color: ${MUTED}; line-height: 1.5; margin: 0 0 26px; }
          .meta { font-size: 11px; color: ${SUBTLE}; letter-spacing: 0.10em; text-transform: uppercase; padding: 14px 0 8px; border-top: 1px solid ${HAIRLINE}; margin-bottom: 0; }
          .byline { font-size: 11px; color: ${MUTED}; letter-spacing: 0.08em; text-transform: uppercase; padding: 0 0 14px; border-bottom: 1px solid ${HAIRLINE}; margin-bottom: 36px; }
          .byline strong { color: ${INK}; font-weight: 700; letter-spacing: 0.04em; }
          .section { margin-bottom: 28px; page-break-inside: avoid; }
          .section .num { display: inline-block; font-size: 11px; font-weight: 700; color: ${SIGNAL_BLUE}; letter-spacing: 0.14em; margin-right: 12px; vertical-align: top; }
          .section h2 { display: inline-block; font-size: 18px; line-height: 1.3; letter-spacing: -0.005em; margin: 0 0 12px; font-weight: 700; color: ${INK}; }
          .section p { font-size: 15px; line-height: 1.75; color: ${BODY}; margin: 0 0 12px; }
          .signoff { margin-top: 32px; padding-top: 22px; border-top: 1px solid ${HAIRLINE}; font-size: 12.5px; color: ${MUTED}; line-height: 1.65; }
          .signoff strong { color: ${INK}; font-weight: 700; }
        `}</style>
      </head>
      <body>
        <div className="doc">
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img src="/logo-black.png" className="logo" alt="Body Recode" />
          <div className="eyebrow">Weekly Pattern Report</div>
          <h1>{data.memberName}, here is your week.</h1>
          <p className="sub">Three observations about where your signal is right now and the one thing worth holding.</p>
          <div className="meta">{meta}</div>
          <div className="byline">By <strong>Kade Dunstone</strong> · Founder, Body Recode</div>

          {SECTIONS.map((s, i) => (
            <div key={s.key} className="section">
              <div>
                <span className="num">{String(i + 1).padStart(2, '0')}</span>
                <h2>{s.label}</h2>
              </div>
              {data.sections[s.key].split(/\n+/).map((p, idx) => <p key={idx}>{p}</p>)}
            </div>
          ))}

          <div className="signoff">
            Designed by <strong>Kade Dunstone</strong>. Generated by the Body Recode engine, the same framework Kade uses with coaching clients. Read this once. Decide on the one focus. Bring observations into your next weekly check-in.
          </div>
        </div>
      </body>
    </html>
  )
}
