/**
 * A backup of the whole database that does not depend on Docker, pg_dump, or
 * anything Supabase has to do for us.
 *
 * WHY THIS EXISTS (20 September 2026). Auditing the "know when it breaks"
 * board step turned up something worse than the untested restore it was
 * supposed to cover: THERE WAS NO BACKUP AT ALL. The Supabase command line
 * tool needs Docker to take a dump, Docker is not installed on this machine,
 * pg_dump is not installed either, and nothing in Dropbox was a database
 * backup. Every copy of this data lived inside one Supabase project, and if
 * that project were deleted, billed into suspension or compromised, the
 * recovery path was to ask Supabase nicely.
 *
 * WHAT THIS IS, AND WHAT IT IS NOT. It reads every row of every table through
 * the same interface the application uses and writes it as JSON. That is a
 * DATA backup. It is not a schema dump: the schema lives in sql/ in git, which
 * is version controlled and older than any of this data, so the pair of them
 * is a complete recovery story. It does not capture storage buckets (progress
 * photographs, blood panel files), which are named as a gap rather than
 * silently missed.
 *
 * HEALTH INFORMATION. The output contains client health information, so it is
 * written to Dropbox rather than anywhere public, and the file list is printed
 * rather than the contents. Retention follows the seven years the privacy
 * policy states, which means old backups are NOT to be left lying around
 * indefinitely: prune them when the practice has a retention routine.
 */
import { createClient } from '@supabase/supabase-js'
import { mkdirSync, writeFileSync, readFileSync } from 'fs'
import { join } from 'path'

// Load .env.local ourselves. THE BACKUP HAS TO WORK FROM A PLAIN TERMINAL,
// because this is the one command Kade runs by hand, and a backup that only
// runs when the environment happens to be loaded is a backup that does not run.
// Found 20 Sep 2026: the first attempt to use it from a clean shell failed
// outright.
try {
  for (const line of readFileSync(join(process.cwd(), '.env.local'), 'utf8').split('\n')) {
    const m = line.match(/^([A-Z0-9_]+)=(.*)$/)
    if (m && !process.env[m[1]]) process.env[m[1]] = m[2].replace(/^["']|["']$/g, '')
  }
} catch {
  // Running somewhere without the file: fall back to whatever is set already.
}

const admin = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.SUPABASE_SERVICE_ROLE_KEY!)

const ROOT = join(process.env.HOME!, 'Dropbox', '01_BODY_RECODE', '00_Project_HQ', '09_Archive_and_Backups', 'database')
const PAGE = 1000

async function listTables(): Promise<string[]> {
  // Asked of the database rather than kept in a list here, because a
  // hand-maintained list fails silently the first time somebody adds a table
  // and forgets. See sql/2026-09-20_backup_table_list.sql.
  const { data, error } = await admin.rpc('backup_table_list')
  if (error) throw new Error(`Could not read the table list: ${error.message}`)
  if (!Array.isArray(data) || data.length === 0) throw new Error('The table list came back empty, which cannot be right.')
  return data as string[]
}

async function dumpTable(table: string): Promise<{ table: string; rows: number; error?: string }> {
  const all: unknown[] = []
  let from = 0
  for (;;) {
    const { data, error } = await admin.from(table).select('*').range(from, from + PAGE - 1)
    if (error) return { table, rows: 0, error: error.message }
    if (!data || data.length === 0) break
    all.push(...data)
    if (data.length < PAGE) break
    from += PAGE
  }
  return { table, rows: all.length, data: all } as { table: string; rows: number; data: unknown[] }
}


interface SchemaSnapshot {
  taken_at: string
  types: Array<{ name: string; values: string[] | null }>
  tables: Array<{
    table: string
    columns: Array<{ name: string; type: string; not_null: boolean; default: string | null }>
    constraints: Array<{ name: string; definition: string }>
    indexes: string[]
    rls_enabled: boolean
  }>
  policies: Array<{ table: string; name: string; command: string; roles: string; using: string | null; with_check: string | null }>
  functions: Array<{ name: string; definition: string }>
}

/**
 * The snapshot as runnable SQL, so recovery does not depend on anybody being
 * able to read JSON at the worst possible moment. Deliberately plain: create
 * the tables, then the constraints, then the indexes, then the policies.
 */
function renderSchemaSql(s: SchemaSnapshot): string {
  const out: string[] = [
    '-- Body Recode schema, captured ' + s.taken_at,
    '-- Generated by scripts/backup-database.ts from the live database, because',
    '-- the core tables have no CREATE TABLE in the repository.',
    '--',
    '-- REHEARSED on 20 September 2026 against an empty PostgreSQL 17. The first',
    '-- attempt built 68 of 116 tables and threw 1,015 errors, all from the same',
    '-- two causes: the `extensions` and `auth` schemas are Supabase-provided and',
    '-- do not exist elsewhere, so every table whose id defaults to a generated',
    '-- UUID failed, and everything referencing those tables cascaded. The',
    '-- preamble below is what closes that gap. It is why this file is generated',
    '-- rather than hand-written: nobody would have remembered.',
    '--',
    '-- This does NOT carry Supabase storage, realtime, or the real auth schema.',
    '-- The auth.users table below is a STUB so foreign keys resolve: restoring',
    '-- into a real Supabase project should skip it and let Supabase own auth.',
    '',
    '-- Prerequisites, so this runs against a plain PostgreSQL.',
    'create schema if not exists extensions;',
    'create extension if not exists "uuid-ossp" with schema extensions;',
    'create extension if not exists pgcrypto with schema extensions;',
    'create schema if not exists auth;',
    'create table if not exists auth.users (id uuid primary key);',
    '-- Stubs so the policies below can be created. Supabase provides the real',
    '-- ones; a restore into a real project should skip these two.',
    "create or replace function auth.uid() returns uuid language sql stable as $fn$ select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid $fn$;",
    "create or replace function auth.role() returns text language sql stable as $fn$ select coalesce(nullif(current_setting('request.jwt.claim.role', true), ''), 'anon') $fn$;",
    "create or replace function auth.jwt() returns jsonb language sql stable as $fn$ select coalesce(nullif(current_setting('request.jwt.claims', true), ''), '{}')::jsonb $fn$;",
    "do $$ begin",
    "  if not exists (select 1 from pg_roles where rolname = 'anon') then create role anon nologin; end if;",
    "  if not exists (select 1 from pg_roles where rolname = 'authenticated') then create role authenticated nologin; end if;",
    "  if not exists (select 1 from pg_roles where rolname = 'service_role') then create role service_role nologin; end if;",
    'end $$;',
    '',
  ]
  if (s.types?.length) {
    out.push('-- Custom types, before the tables that use them.')
    for (const t of s.types) {
      if (!t.values?.length) continue
      out.push(`do $$ begin create type public.${t.name} as enum (${t.values.map(v => `'${v.replace(/'/g, "''")}'`).join(', ')}); exception when duplicate_object then null; end $$;`)
    }
    out.push('')
  }

  for (const t of s.tables) {
    // A default that references another column is not legal in CREATE TABLE
    // and made one table fail outright in the rehearsal. The column is created
    // without it and the default is noted, rather than losing the table.
    const deferred: string[] = []
    out.push(`create table if not exists public.${t.table} (`)
    out.push(
      t.columns
        .map(c => {
          // A default is not legal in CREATE TABLE if it refers to ANY column
          // of the same table. The first version of this check only looked for
          // trigger-style NEW./OLD. references and missed a real one:
          // be_ad_campaigns.cost_per_lead defaults to a CASE over spend and
          // leads_count, which cost us that whole table in the rehearsal.
          const otherColumns = t.columns.filter(o => o.name !== c.name).map(o => o.name)
          const selfReferencing = Boolean(
            c.default &&
              (/\b(?:new|old)\./i.test(c.default) ||
                otherColumns.some(name => new RegExp(`\\b${name}\\b`).test(c.default as string))),
          )
          // Kept on one line and commented out: a multi-line CASE pasted raw
          // into the file is itself a syntax error, which is what the last
          // rehearsal run tripped over.
          if (selfReferencing) {
            deferred.push(
              `-- ${t.table}.${c.name} had a default computed from other columns, which CREATE TABLE cannot express.`,
              `-- Re-apply by hand: alter table public.${t.table} alter column ${c.name} set default ${String(c.default).replace(/\s+/g, ' ')};`,
            )
          }
          return `  ${c.name} ${c.type}${c.default && !selfReferencing ? ` default ${c.default}` : ''}${c.not_null ? ' not null' : ''}`
        })
        .join(',\n'),
    )
    out.push(');')
    for (const d of deferred) out.push(d)
    if (t.rls_enabled) out.push(`alter table public.${t.table} enable row level security;`)
    out.push('')
  }
  // Primary and unique keys FIRST. The rehearsal on 20 Sep produced 55 errors
  // reading "no unique constraint matching given keys" purely because foreign
  // keys were being added before the keys they point at existed.
  out.push('-- Primary and unique keys')
  for (const t of s.tables) {
    for (const c of t.constraints) {
      if (/^(PRIMARY KEY|UNIQUE)/i.test(c.definition)) {
        out.push(`alter table public.${t.table} add constraint ${c.name} ${c.definition};`)
      }
    }
  }
  out.push('', '-- Foreign keys and checks')
  for (const t of s.tables) {
    for (const c of t.constraints) {
      if (!/^(PRIMARY KEY|UNIQUE)/i.test(c.definition)) {
        out.push(`alter table public.${t.table} add constraint ${c.name} ${c.definition};`)
      }
    }
  }
  // Indexes that a constraint already created are skipped: adding a primary
  // key creates its index, and re-issuing it errors as "already exists".
  out.push('', '-- Indexes')
  for (const t of s.tables) {
    const constraintNames = new Set(t.constraints.map(c => c.name))
    for (const i of t.indexes) {
      const m = i.match(/CREATE (?:UNIQUE )?INDEX (\S+) ON/i)
      if (m && constraintNames.has(m[1])) continue
      out.push(`${i};`)
    }
  }
  // Functions BEFORE policies. The rehearsal produced "function is_coach()
  // does not exist" purely because the policies that call it were created
  // first.
  out.push('', '-- Functions')
  for (const f of s.functions) out.push(`${f.definition};`, '')
  out.push('', '-- Row level security policies')
  for (const p of s.policies) {
    out.push(
      `create policy "${p.name}" on public.${p.table} for ${p.command.toLowerCase()} to ${p.roles.replace(/[{}]/g, '')}` +
        `${p.using ? ` using (${p.using})` : ''}${p.with_check ? ` with check (${p.with_check})` : ''};`,
    )
  }
  return out.join('\n')
}

async function main() {
  const tables = await listTables()
  console.log(`${tables.length} tables to back up\n`)

  const stamp = new Date().toISOString().slice(0, 19).replace(/[:T]/g, '-')
  const dir = join(ROOT, stamp)
  mkdirSync(dir, { recursive: true })

  const manifest: Array<{ table: string; rows: number; error?: string }> = []
  let totalRows = 0
  let failed = 0

  for (const t of tables) {
    const res = await dumpTable(t) as { table: string; rows: number; error?: string; data?: unknown[] }
    if (res.error) {
      failed++
      console.log(`  FAILED  ${t}: ${res.error}`)
      manifest.push({ table: t, rows: 0, error: res.error })
      continue
    }
    writeFileSync(join(dir, `${t}.json`), JSON.stringify(res.data ?? [], null, 0))
    totalRows += res.rows
    manifest.push({ table: t, rows: res.rows })
    console.log(`  ok      ${t.padEnd(38)} ${res.rows}`)
  }

  // The shape of the database, saved beside the rows. Added 20 Sep 2026 after
  // finding that six core tables (clients, intakes, cffs, weekly_checkins,
  // baselines, leads) have NO CREATE TABLE anywhere in the repository: they
  // were made through the Supabase interface and never written down. Without
  // this, a backup is a pile of rows with nowhere to put them back.
  let schemaSaved = false
  try {
    const { data: schema, error: schemaErr } = await admin.rpc('schema_snapshot')
    if (schemaErr) throw new Error(schemaErr.message)
    writeFileSync(join(dir, '_schema.json'), JSON.stringify(schema, null, 2))
    writeFileSync(join(dir, '_schema.sql'), renderSchemaSql(schema as SchemaSnapshot))
    schemaSaved = true
    const t = (schema as SchemaSnapshot).tables?.length ?? 0
    const p = (schema as SchemaSnapshot).policies?.length ?? 0
    const f = (schema as SchemaSnapshot).functions?.length ?? 0
    console.log(`\n  schema captured: ${t} tables, ${p} policies, ${f} functions`)
  } catch (err) {
    failed++
    console.log(`\n  FAILED to capture the schema: ${err instanceof Error ? err.message : String(err)}`)
  }

  writeFileSync(
    join(dir, '_manifest.json'),
    JSON.stringify({ taken_at: new Date().toISOString(), tables: manifest, total_rows: totalRows, failed, schema_saved: schemaSaved }, null, 2),
  )

  console.log('')
  console.log(`${tables.length} tables, ${totalRows} rows, ${failed} failed`)
  console.log(`written to ${dir}`)
  if (failed > 0) {
    console.log('')
    console.log('A FAILED TABLE MEANS THIS BACKUP IS INCOMPLETE. Do not treat it as one.')
    process.exit(1)
  }
  console.log('BACKUP COMPLETE')
}
main()
