// Branded "what's new in your portal" update email to active coaching clients.
//
// Headlines the new Health Markers (blood test upload) feature, then rounds up
// the other recent client-facing additions (Readings, weekly check-in feedback,
// in-gym workout logging). Composed entirely from the email design helpers so it
// matches the system look (Pure White / Signal Blue), same as Samantha's refund
// email.
//
// Default mode is PREVIEW: sends a single [PREVIEW] copy to kade@bodyrecode.au
// with a sample name + the portal login link, so Kade sees the exact look first.
//
// Pass --live to broadcast: loops every active client and sends each a
// personalised copy with their own first name + their own portal link.
//
// Usage:
//   cd ~/body-recode-mvp && set -a && source .env.local && set +a && npx tsx scripts/client-product-update-email.ts
//   cd ~/body-recode-mvp && set -a && source .env.local && set +a && npx tsx scripts/client-product-update-email.ts --live

import { createClient } from '@supabase/supabase-js'
import { Resend } from 'resend'
import {
  darkEmailShell,
  emailLogo, emailEyebrow, emailHeading, emailDivider, emailBody,
  emailFeaturedCard, emailNumberedList, emailStatusCard, emailCta, emailUrlFallback,
} from '../src/lib/email-shell'
import { darkEmailSignature } from '../src/lib/email-signature'
import { portalUrl, portalLoginUrl } from '../src/lib/app-url'

const LIVE = process.argv.includes('--live')

// "Signal" - the recurring Body Recode portal-update series. Bump SIGNAL_ISSUE
// and SIGNAL_DATE each send; the standfirst line stays constant so the series
// reads the same way every issue.
const SIGNAL_ISSUE = 'No. 02'  // No. 01 was the 2026-05-12 update (pre-Signal branding)
const SIGNAL_DATE = 'June 2026'
const SIGNAL_STANDFIRST = 'What your portal can now see, and what it means for your coaching.'

const SUBJECT_LIVE = `Signal ${SIGNAL_ISSUE}: a few new things inside your portal`
const PREVIEW_TEXT = 'Health Markers, the Block-End Reading, your Readings and more are now live.'

// Brand graphics generated by scripts/generate-update-email-graphics.py, served
// from body-recode-mvp/public/email/ once deployed. Inline (not attached) so they
// render in the body. Alt text carries the message when images are blocked.
const ASSET_BASE = 'https://app.bodyrecode.au/email'

const FONT_STACK = "-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif"

function emailImage(file: string, alt: string): string {
  return `<img src="${ASSET_BASE}/${file}" width="600" alt="${alt}" style="display:block;width:100%;max-width:600px;height:auto;border:0;border-radius:14px;margin:0 0 30px;" />`
}

/** Full-width hairline rule (the masthead separator, distinct from the short blue emailDivider). */
function fullRule(top = 0, bottom = 24): string {
  return `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin:${top}px 0 ${bottom}px;"><tr><td height="1" bgcolor="#E5E5E5" style="background-color:#E5E5E5;line-height:1px;font-size:0;">&nbsp;</td></tr></table>`
}

/** The recurring "Signal" masthead: series name + issue + date, headline, standfirst. */
function signalMasthead(): string {
  const series = `<p style="font-size:12px;font-weight:800;letter-spacing:0.16em;text-transform:uppercase;margin:0 0 18px;font-family:${FONT_STACK};"><span style="color:#1B6DFC;">Signal</span><span style="color:#C8C8C8;">&nbsp;&nbsp;·&nbsp;&nbsp;</span><span style="color:#999999;">${SIGNAL_ISSUE}&nbsp;&nbsp;·&nbsp;&nbsp;${SIGNAL_DATE}</span></p>`
  const heading = `<h1 style="font-size:34px;font-weight:800;letter-spacing:-0.025em;line-height:1.15;color:#1A1A1A;margin:0 0 18px;font-family:${FONT_STACK};">A few new things<br/>inside your portal</h1>`
  const standfirst = `<p style="font-size:18px;font-weight:400;font-style:italic;color:#6B6B6B;line-height:1.55;margin:0 0 34px;font-family:${FONT_STACK};">${SIGNAL_STANDFIRST}</p>`
  return `${fullRule(8, 22)}${series}${heading}${standfirst}`
}

function firstNameOf(name: string | null): string {
  if (!name) return 'there'
  return name.trim().split(/\s+/)[0] || 'there'
}

function buildHtml(firstName: string, portalLink: string): string {
  const inner = `
${emailLogo()}
${signalMasthead()}
${emailBody(`Hi ${firstName},`)}
${emailBody('A quick walk-through of what has been added to your portal over the last few weeks. None of it changes what we are doing together. It gives both of us more signal to work with, and gives you more to see.', { bottom: 16 })}
${emailBody('<strong style="color:#1A1A1A;">First, the look.</strong> You will have noticed the whole platform has moved from the old dark theme to a clean, light one. That was deliberate: your information is easier to read at a glance, it holds up far better on a phone (the old dark screens inverted badly in some apps), and the calmer layout keeps the focus on what your body is actually telling us rather than the interface around it.', { bottom: 36 })}
${emailEyebrow('The big one · Health Markers')}
${emailHeading('Your blood work, working for your training.', { size: 26 })}
${emailDivider()}
${emailBody('Most blood panels get a thirty-second glance from a GP and then sit in a drawer. From today, you can upload yours straight to your portal: a PDF, or even a photo of the page. From there it stops being a dead sheet of numbers and starts pulling its weight inside your coaching.', { bottom: 24 })}
${emailImage('email-health-markers.png', 'Health Markers card: each blood marker shown against your lab\'s own range, most in range, one flagged to review with your GP')}
${emailFeaturedCard(
  emailNumberedList([
    'Upload it in seconds. A PDF or a clear photo of the results page is all it takes.',
    'Every marker is read against your lab’s own reference ranges, so nothing gets lost in the noise.',
    'Anything sitting outside range is flagged, accounted for in your training and nutrition, and pointed back to your GP where it belongs.',
  ]),
  { eyebrow: 'What happens when you upload' },
)}
${emailBody('To be clear: I am not your doctor and this is never a diagnosis. Anything medical stays with your GP, and I will always point you back to them when that is the right call. This simply turns your bloods into one more honest signal about what is actually happening inside your body, sitting alongside everything else we track.', { bottom: 24 })}
${emailFeaturedCard(
  `${emailBody('<strong style="color:#1A1A1A;">Do this one this week.</strong> If you have had blood work in the last six to twelve months, dig it out and upload it now. If you have not, it is worth booking a simple panel with your GP. The sooner your bloods are in your portal, the sooner they start shaping your training and nutrition, so please get them in as soon as you can.', { size: 15, bottom: 0 })}`,
  { eyebrow: 'Your move' },
)}
${emailCta({ href: `${portalLink}/bloods`, label: 'Upload your blood test' })}
${emailStatusCard({
  eyebrow: 'Where this is heading',
  headline: 'One upload today. A moving picture tomorrow.',
  body: 'This is the first step of something much bigger. As you add panels over time, the system builds a view of how your markers move across months, not a single snapshot, and starts reading those trends against your training, nutrition and recovery. The direction we are building toward: your plan adapting to what your bloods, your check-ins and your logged sessions are saying together, and an early nudge when something begins to drift long before it becomes a problem. Today is where that starts.',
})}
${emailEyebrow('New · Block-End Reading')}
${emailHeading('The trend, not the snapshot.', { size: 26 })}
${emailDivider()}
${emailBody('When you finish a training block, you now get a block-end reading: a step back from the week-to-week that reads how your body moved across the whole block, not just where it sits on any one day. Where you started, what shifted, what held steady, and what it sets up next. It is the same idea as the blood work above, applied to your training: the trend over time, not the snapshot.', { bottom: 24 })}
${emailImage('email-block-end-reading.png', 'Block-End Reading card: section 01, Where this block started, a plain-language read of how your signal moved across the block')}
${emailEyebrow('Also new')}
${emailDivider()}
${emailBody('<strong style="color:#1A1A1A;">Your Readings.</strong> Your program and nutrition plan now sit underneath plain-English readings that explain the why, not just the what. There is a reading for your training block, one for your nutrition plan, and one that accounts for any medications or supports you have told me about.', { bottom: 16 })}
${emailBody('<strong style="color:#1A1A1A;">Written feedback on every check-in.</strong> When you submit a weekly check-in you now get a written response back from me, on the portal and by email: how I am reading the week, any reframe if the picture has shifted, and the one thing to hold for the week ahead.', { bottom: 16 })}
${emailBody('<strong style="color:#1A1A1A;">Log your sets while you train.</strong> You can now log your training set by set, in the gym, as you go. It snapshots what was prescribed so we can both see how the actual work compared to the plan when we look back.', { bottom: 28 })}
${emailStatusCard({
  eyebrow: 'No action needed',
  headline: 'Use what is useful, ignore what is not.',
  body: 'Nothing here needs doing today. The blood upload is there the moment you want it, and everything else is already on your portal.',
})}
${emailEyebrow('Your part in this')}
${emailHeading('The system gets sharper every week you check in.', { size: 24 })}
${emailDivider()}
${emailBody('There is one exception to all of that, and it is the most important thing in this email. Everything above runs on a single input: the signal you give me each week. Your weekly check-ins are the raw material the whole system reads.', { bottom: 16 })}
${emailBody('Every time you complete one, your readings get sharper, I see your week clearly, and the trends behind your block-end reading and what comes next get more accurate. The honest weeks, the flat weeks, the strong weeks: they all count. You are not just using this platform, you are shaping how it develops. The more consistent your signal, the more the system can do, for you and for everyone we build it for next.', { bottom: 24 })}
${emailFeaturedCard(
  emailBody('Two minutes, every week. It is the highest-leverage thing you do here, and it is the one thing only you can give.', { size: 15, bottom: 0 }),
  { eyebrow: 'If you do one thing' },
)}
${emailCta({ href: portalLink, label: 'Open your portal' })}
${emailUrlFallback(portalLink)}
${emailBody('Any questions, just hit reply.', { size: 15, bottom: 4 })}
${darkEmailSignature()}
`
  return darkEmailShell(inner, { previewText: PREVIEW_TEXT })
}

async function main() {
  if (!process.env.RESEND_API_KEY) {
    console.error('RESEND_API_KEY missing.')
    process.exit(1)
  }
  const resend = new Resend(process.env.RESEND_API_KEY)
  const FROM = 'Kade at Body Recode <kade@bodyrecode.au>'

  if (!LIVE) {
    const html = buildHtml('Kade', portalLoginUrl())
    console.log('Mode      : PREVIEW (sending one copy to Kade only)')
    console.log(`Subject   : [PREVIEW] ${SUBJECT_LIVE}`)
    console.log('To        : kade@bodyrecode.au')
    const result = await resend.emails.send({
      from: FROM,
      to: 'kade@bodyrecode.au',
      subject: `[PREVIEW] ${SUBJECT_LIVE}`,
      html,
    })
    console.log('\nResend result:')
    console.log(JSON.stringify(result, null, 2))
    return
  }

  // LIVE broadcast to every active client.
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY
  if (!url || !key) {
    console.error('Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY')
    process.exit(1)
  }
  const admin = createClient(url, key)

  const { data: clients, error } = await admin
    .from('clients')
    .select('id, name, email, onboarding_token, active')
    .eq('active', true)
    .order('created_at', { ascending: false })

  if (error) {
    console.error('Failed to load clients:', error)
    process.exit(1)
  }

  const recipients = (clients ?? []).filter(c => c.email && c.onboarding_token)
  const skipped = (clients ?? []).filter(c => !c.email || !c.onboarding_token)

  console.log(`Mode      : LIVE broadcast`)
  console.log(`Active    : ${(clients ?? []).length}`)
  console.log(`Sendable  : ${recipients.length}`)
  if (skipped.length) {
    console.log(`Skipped   : ${skipped.length} (missing email or portal token)`)
    skipped.forEach(c => console.log(`            - ${c.name ?? c.id} (${c.email ?? 'no email'})`))
  }
  console.log('')

  let sent = 0
  for (const c of recipients) {
    const firstName = firstNameOf(c.name)
    const html = buildHtml(firstName, portalUrl(c.onboarding_token as string))
    try {
      const result = await resend.emails.send({
        from: FROM,
        to: c.email as string,
        subject: SUBJECT_LIVE,
        html,
      })
      if (result.error) {
        console.log(`  FAIL  ${c.email}  ${JSON.stringify(result.error)}`)
      } else {
        sent++
        console.log(`  sent  ${c.email}  (${result.data?.id})`)
      }
    } catch (err) {
      console.log(`  FAIL  ${c.email}  ${err}`)
    }
  }

  console.log(`\nDone. ${sent}/${recipients.length} sent.`)
}

main().then(() => process.exit(0)).catch(err => { console.error(err); process.exit(1) })
