/**
 * Provision a new Founding Ten partner tenant from a JSON config file.
 *
 * Replaces the manual seed-SQL fill-in-placeholders flow. Reads a config
 * at `partners/<slug>.json`, validates it, emits a fully-populated SQL
 * seed file to `~/Dropbox/01_BODY_RECODE/06_SAAS_PLATFORM_BUILD/sql/`,
 * and optionally creates the coach's Supabase auth user in one step.
 *
 * Usage:
 *   npx tsx --env-file=.env.local scripts/provision-tenant.ts <slug>              # dry-run: emit SQL only
 *   npx tsx --env-file=.env.local scripts/provision-tenant.ts <slug> --auth-user  # also create auth.users row
 *   npx tsx --env-file=.env.local scripts/provision-tenant.ts <slug> --apply      # emit SQL + create auth user + apply via supabase CLI
 *
 * Idempotent: safe to re-run. Existing auth user is left alone. Existing
 * tenant_config row is left alone (ON CONFLICT DO NOTHING in the SQL).
 *
 * When adding a new partner:
 *   1. Copy partners/_template.json -> partners/<slug>.json
 *   2. Fill in every field (any {{...}} left in output means unfilled)
 *   3. Add the doctrine preset id (see src/lib/doctrine-parameters-presets.ts)
 *   4. `npx tsx scripts/provision-tenant.ts <slug>` to preview the SQL
 *   5. Review the SQL, then re-run with --apply once satisfied
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { join } from 'node:path'
import { execSync } from 'node:child_process'
import { homedir } from 'node:os'
import { createClient } from '@supabase/supabase-js'
import { getPreset } from '../src/lib/doctrine-parameters-presets'

// ── Config type + validator ─────────────────────────────────────────────
type PartnerConfig = {
  tenantId: string
  apexDomain: string
  coach: {
    email: string
    firstName: string
    fullName: string
    location: string
    credentials: string
    photoUrl: string
    phoneE164NoPlus: string
    brandInstagram: string
    personalInstagram: string
  }
  brand: {
    name: string
    nameWithMark: string
    tagline: string
    logoUrlLight: string
    logoUrlDark: string
    accentColor: string
  }
  products: {
    reportPrice: number
    blueprintPrice: number
    membershipPrice: number
    membershipName: string
    coachingPackage2xPrice: number
    coachingPackagePriceLabel: string
  }
  licence: {
    tenantId: string
    poweredBy: boolean
    partnerBillingTier: 'launch' | 'studio'
    lockedSetupFeeCents: number
    lockedSubscriptionCents: number
    lockedPerActiveClientCents: number
  }
  modality: {
    id: string
    label: string
    doctrineMode: 'A' | 'B'
  }
  doctrinePreset: string
}

function readConfig(slug: string): PartnerConfig {
  const path = join(process.cwd(), 'partners', `${slug}.json`)
  if (!existsSync(path)) {
    throw new Error(`No config at ${path}. Copy partners/_template.json to partners/${slug}.json and fill it in.`)
  }
  const raw = JSON.parse(readFileSync(path, 'utf-8')) as PartnerConfig
  const errors: string[] = []
  const req = (path: string, val: unknown) => {
    if (val === undefined || val === null || val === '') errors.push(path)
  }
  req('tenantId', raw.tenantId)
  req('apexDomain', raw.apexDomain)
  req('coach.email', raw.coach?.email)
  req('coach.fullName', raw.coach?.fullName)
  req('coach.firstName', raw.coach?.firstName)
  req('brand.name', raw.brand?.name)
  req('brand.tagline', raw.brand?.tagline)
  req('brand.accentColor', raw.brand?.accentColor)
  req('licence.tenantId', raw.licence?.tenantId)
  req('modality.id', raw.modality?.id)
  req('doctrinePreset', raw.doctrinePreset)
  if (errors.length > 0) {
    throw new Error(`Config validation failed. Missing/empty: ${errors.join(', ')}`)
  }
  if (raw.tenantId !== raw.licence.tenantId) {
    throw new Error(`tenantId at top level ("${raw.tenantId}") must match licence.tenantId ("${raw.licence.tenantId}").`)
  }
  const preset = getPreset(raw.doctrinePreset)
  if (!preset) {
    throw new Error(`Unknown doctrinePreset: "${raw.doctrinePreset}". See src/lib/doctrine-parameters-presets.ts for available ids.`)
  }
  return raw
}

// ── SQL generator ───────────────────────────────────────────────────────
function generateSeedSql(cfg: PartnerConfig, coachUuid: string, dateIso: string): string {
  const preset = getPreset(cfg.doctrinePreset)!
  const dp = preset.parameters

  const jsonbLit = (obj: unknown) => `'${JSON.stringify(obj).replace(/'/g, "''")}'::jsonb`
  const banned = jsonbLit(dp.bannedPhrases)
  const subs = jsonbLit(dp.terminologySubstitutions)

  return `-- ${cfg.brand.name} · Founding Partner tenant seed
-- Generated by scripts/provision-tenant.ts on ${dateIso}
-- Config source: partners/${cfg.tenantId}.json
-- Doctrine preset: ${preset.id} (${preset.label})
--
-- Idempotent via ON CONFLICT (coach_id) DO NOTHING.
-- Apply via: supabase db query --linked < ${dateIso}_${cfg.tenantId}_seed.sql

INSERT INTO tenant_config (coach_id, brand, coach, products, licence, modality)
VALUES (
  '${coachUuid}',
  jsonb_build_object(
    'name', ${sqlStr(cfg.brand.name)},
    'nameWithMark', ${sqlStr(cfg.brand.nameWithMark)},
    'tagline', ${sqlStr(cfg.brand.tagline)},
    'logoUrlLight', ${sqlStr(cfg.brand.logoUrlLight)},
    'logoUrlDark', ${sqlStr(cfg.brand.logoUrlDark)},
    'apexDomain', ${sqlStr(cfg.apexDomain)},
    'marketingDomain', ${sqlStr(`https://${cfg.apexDomain}`)},
    'performanceDomain', ${sqlStr(`https://scorecard.${cfg.apexDomain}`)},
    'appDomain', ${sqlStr(`https://app.${cfg.apexDomain}`)},
    'supportEmail', ${sqlStr(`hello@${cfg.apexDomain}`)},
    'replyToEmail', ${sqlStr(`${cfg.coach.firstName.toLowerCase()}@replies.${cfg.apexDomain}`)},
    'fromEmail', ${sqlStr(`${cfg.coach.firstName.toLowerCase()}@send.${cfg.apexDomain}`)},
    'accentColor', ${sqlStr(cfg.brand.accentColor)}
  ),
  jsonb_build_object(
    'firstName', ${sqlStr(cfg.coach.firstName)},
    'fullName', ${sqlStr(cfg.coach.fullName)},
    'email', ${sqlStr(cfg.coach.email)},
    'adminEmail', ${sqlStr(cfg.coach.email)},
    'photoUrl', ${sqlStr(cfg.coach.photoUrl)},
    'location', ${sqlStr(cfg.coach.location)},
    'credentials', ${sqlStr(cfg.coach.credentials)},
    'instagramHandle', ${sqlStr(cfg.coach.brandInstagram)},
    'personalInstagramHandle', ${sqlStr(cfg.coach.personalInstagram)},
    'whatsAppNumber', ${sqlStr(cfg.coach.phoneE164NoPlus)}
  ),
  jsonb_build_object(
    'scorecardName', 'Body State Scorecard',
    'reportProductName', 'Body Decode Report',
    'reportPrice', ${cfg.products.reportPrice},
    'challengeName', '14-Day Body Decode Challenge',
    'challengePrice', 0,
    'blueprintName', '6-Week Body Rewire Blueprint',
    'blueprintPrice', ${cfg.products.blueprintPrice},
    'membershipName', ${sqlStr(cfg.products.membershipName)},
    'membershipPrice', ${cfg.products.membershipPrice},
    'coachingPackage2xPrice', ${cfg.products.coachingPackage2xPrice},
    'coachingPackagePriceLabel', ${sqlStr(cfg.products.coachingPackagePriceLabel)}
  ),
  jsonb_build_object(
    'tenantId', ${sqlStr(cfg.licence.tenantId)},
    'poweredBy', ${cfg.licence.poweredBy},
    'version', to_char(now(), 'YYYY-MM-DD'),
    'stripeAccountId', NULL,
    'stripeAccountStatus', NULL,
    'twilioSubaccountSid', NULL,
    'twilioMessagingServiceSid', NULL,
    'partnerBilling', jsonb_build_object(
      'tier', ${sqlStr(cfg.licence.partnerBillingTier)},
      'customerId', NULL,
      'subscriptionId', NULL,
      'activeFrom', to_char(now(), 'YYYY-MM-DD'),
      'lockedSetupFeeCents', ${cfg.licence.lockedSetupFeeCents},
      'lockedSubscriptionCents', ${cfg.licence.lockedSubscriptionCents},
      'lockedPerActiveClientCents', ${cfg.licence.lockedPerActiveClientCents},
      'setupFeeStatus', 'invoiced'
    ),
    'doctrineParameters', jsonb_build_object(
      'voiceTone', ${sqlStr(dp.voiceTone)},
      'bannedPhrases', ${banned},
      'terminologySubstitutions', ${subs},
      'checkinCoachingGuidance', ${sqlStr(dp.checkinCoachingGuidance)},
      'programGenerationGuidance', ${sqlStr(dp.programGenerationGuidance)},
      'nutritionGenerationGuidance', ${sqlStr(dp.nutritionGenerationGuidance)}
    )
  ),
  jsonb_build_object(
    'id', ${sqlStr(cfg.modality.id)},
    'label', ${sqlStr(cfg.modality.label)},
    'doctrineMode', ${sqlStr(cfg.modality.doctrineMode)}
  )
)
ON CONFLICT (coach_id) DO NOTHING;

-- Tenant domains row so host routing picks it up
INSERT INTO tenant_domains (tenant_id, coach_id, domain, is_primary)
VALUES (${sqlStr(cfg.licence.tenantId)}, '${coachUuid}', ${sqlStr(cfg.apexDomain)}, true)
ON CONFLICT (domain) DO NOTHING;

-- Verification
SELECT
  licence->>'tenantId' AS tenant_id,
  brand->>'name' AS brand_name,
  coach->>'fullName' AS coach_name,
  modality->>'id' AS modality,
  licence->'partnerBilling'->>'tier' AS billing_tier,
  licence->'doctrineParameters'->>'voiceTone' AS voice_tone
FROM tenant_config
WHERE coach_id = '${coachUuid}';

-- Post-seed manual follow-ups (still owner-of-tenant work):
--   1. Add DNS: ${cfg.apexDomain} CNAME -> cname.vercel-dns.com
--   2. Add to Vercel env NEXT_PUBLIC_TENANT_DOMAIN_MAP: ${cfg.apexDomain}:${cfg.licence.tenantId}
--   3. Stripe Connect onboarding: login as ${cfg.coach.firstName} at /dashboard/settings/tenant
--   4. Twilio Subaccount + AU number in Kade's console; write SIDs back to licence.twilioSubaccountSid
--   5. Kade's Stripe: create Customer + Subscription for platform billing; invoice $${cfg.licence.lockedSetupFeeCents / 100} setup
--   6. Verify: ${cfg.coach.firstName} logs in at https://${cfg.apexDomain}/dashboard/settings/tenant
`
}

function sqlStr(s: string): string {
  if (s === null || s === undefined) return 'NULL'
  return `'${String(s).replace(/'/g, "''")}'`
}

// ── Auth-user creation (idempotent) ─────────────────────────────────────
async function ensureAuthUser(email: string): Promise<string> {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY
  if (!url || !key) {
    throw new Error('NEXT_PUBLIC_SUPABASE_URL + SUPABASE_SERVICE_ROLE_KEY required. Use --env-file=.env.local or export them.')
  }
  const admin = createClient(url, key, { auth: { autoRefreshToken: false, persistSession: false } })

  const { data: list, error: listErr } = await admin.auth.admin.listUsers({ perPage: 200 })
  if (listErr) throw new Error(`Auth list failed: ${listErr.message}`)
  const existing = list.users.find((u) => u.email?.toLowerCase() === email.toLowerCase())
  if (existing) {
    console.log(`  → auth.users row already exists: ${existing.id} (${email})`)
    return existing.id
  }

  const { data: created, error: createErr } = await admin.auth.admin.createUser({
    email,
    email_confirm: true,
    user_metadata: { provisioned_by: 'scripts/provision-tenant.ts' },
  })
  if (createErr || !created?.user) throw new Error(`Auth create failed: ${createErr?.message ?? 'unknown'}`)
  console.log(`  → auth.users row created: ${created.user.id} (${email})`)
  return created.user.id
}

// ── SQL apply (via supabase CLI) ────────────────────────────────────────
function applySql(sqlFilePath: string) {
  console.log(`\n  → applying via: supabase db query --linked < ${sqlFilePath}`)
  try {
    execSync(`supabase db query --linked < "${sqlFilePath}"`, { stdio: 'inherit' })
  } catch (err) {
    throw new Error(`supabase CLI apply failed: ${(err as Error).message}`)
  }
}

// ── Main ────────────────────────────────────────────────────────────────
async function main() {
  const slug = process.argv[2]
  const mode = process.argv.includes('--apply')
    ? 'apply'
    : process.argv.includes('--auth-user')
      ? 'auth-user'
      : 'dry-run'

  if (!slug) {
    console.error('Usage: npx tsx --env-file=.env.local scripts/provision-tenant.ts <slug> [--auth-user | --apply]')
    process.exit(1)
  }

  console.log(`\n═══ Provisioning tenant: ${slug} · mode: ${mode} ═══\n`)

  const cfg = readConfig(slug)
  console.log(`Config loaded: partners/${slug}.json`)
  console.log(`  brand: ${cfg.brand.name} (${cfg.brand.tagline})`)
  console.log(`  coach: ${cfg.coach.fullName} <${cfg.coach.email}>`)
  console.log(`  modality: ${cfg.modality.id} (mode ${cfg.modality.doctrineMode})`)
  console.log(`  doctrine preset: ${cfg.doctrinePreset}`)

  // Warn on unfilled placeholders
  const raw = readFileSync(join(process.cwd(), 'partners', `${slug}.json`), 'utf-8')
  const unfilledCount = (raw.match(/\{\{[^}]+\}\}/g) ?? []).length
  if (unfilledCount > 0) {
    console.warn(`\n  ⚠ ${unfilledCount} {{...}} placeholder(s) still in config. Config values above show the raw placeholders. Fill before --apply.`)
  }

  let coachUuid = '00000000-0000-0000-0000-000000000000'
  if (mode === 'auth-user' || mode === 'apply') {
    console.log('\n─── Auth user ───')
    coachUuid = await ensureAuthUser(cfg.coach.email)
  } else {
    console.log('\n  (dry-run: using placeholder UUID; pass --auth-user to actually create the row)')
  }

  console.log('\n─── Generating seed SQL ───')
  const dateIso = new Date().toISOString().slice(0, 10)
  const sql = generateSeedSql(cfg, coachUuid, dateIso)

  const outDir = join(homedir(), 'Dropbox', '01_BODY_RECODE', '06_SAAS_PLATFORM_BUILD', 'sql')
  const outFile = join(outDir, `${dateIso}_${slug}_generated_seed.sql`)
  if (!existsSync(outDir)) {
    console.warn(`  ⚠ output dir does not exist: ${outDir}. Writing to cwd instead.`)
    const fallback = join(process.cwd(), `${dateIso}_${slug}_generated_seed.sql`)
    writeFileSync(fallback, sql, 'utf-8')
    console.log(`  → wrote: ${fallback}`)
  } else {
    writeFileSync(outFile, sql, 'utf-8')
    console.log(`  → wrote: ${outFile}`)
  }

  if (mode === 'apply') {
    console.log('\n─── Applying SQL ───')
    applySql(outFile)
  } else {
    console.log('\n─── Next steps ───')
    console.log(`  Review the SQL, then apply:`)
    console.log(`    supabase db query --linked < "${outFile}"`)
    console.log(`  Or re-run with --apply to do both.`)
  }

  console.log('\n═══ Done ═══\n')
}

main().catch((err) => {
  console.error(`\n✗ ${err.message}\n`)
  process.exit(1)
})
