-- Split nutrition_reading doctrine version into its own column.
--
-- The nutrition_plans table had ONE doctrine_version column that was being
-- written by TWO different generators with DIFFERENT version constants:
--   - generate-nutrition route stamps NUTRITION_DOCTRINE_VERSION (plan version)
--   - generate-nutrition-reading route OVERWROTE that with
--     DOCTRINE_VERSIONS.nutrition_reading (reading version)
--
-- Result: every time a coach regenerated a nutrition reading, the plan's
-- doctrine_version was clobbered with the reading's version. The coach
-- dashboard then saw a mismatch and showed a misleading "Doctrine update
-- available" banner inviting the coach to regenerate the plan — because the
-- plan's stamp had been corrupted by a downstream artefact.
--
-- This migration:
--   1. Adds nutrition_reading_doctrine_version column for the reading stamp
--   2. Backfills the new column with the polluted value where applicable
--      (any plan with a published nutrition reading and a non-null
--      doctrine_version inherits that value into the new column)
--   3. Clears doctrine_version on polluted rows (sets NULL — grandfathered).
--      The plan was generated by my regen script which bypassed the route,
--      so the original stamp was NULL anyway. Restoring NULL is correct.

alter table public.nutrition_plans
  add column if not exists nutrition_reading_doctrine_version text;

comment on column public.nutrition_plans.nutrition_reading_doctrine_version is
  'Doctrine version constant in effect when the nutrition Reading prose was generated (DOCTRINE_VERSIONS.nutrition_reading). Stamped by generate-nutrition-reading route. Separate from doctrine_version (the plan-doctrine stamp set by generate-nutrition route).';

-- Backfill: move polluted reading-version values from doctrine_version into
-- the new column. A row is "polluted" if it has a published reading AND a
-- non-null doctrine_version. (We can't distinguish "set by plan route" vs
-- "set by reading route" historically because they used the same column —
-- but any row with a published reading would have had its doctrine_version
-- overwritten on the most recent reading generation, so the current value is
-- the reading version.)
update public.nutrition_plans
set
  nutrition_reading_doctrine_version = doctrine_version,
  doctrine_version = null
where
  nutrition_reading_published_at is not null
  and doctrine_version is not null;
